---
permalink: upgrade/upgrade-ontap-tools.html 
sidebar: sidebar 
keywords: upgrade 
summary: 'L"aggiornamento è supportato per le implementazioni ha e non ha.' 
---
= Aggiornamento dagli ONTAP tools for VMware vSphere 10.x alla versione 10.5
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile effettuare l'aggiornamento dagli ONTAP tools for VMware vSphere 10.3 o 10.4 alla versione 10.5.  Tuttavia, per eseguire l'aggiornamento dagli strumenti ONTAP 10.0, 10.1 o 10.2 alla versione 10.5, è necessario prima eseguire l'aggiornamento alla versione 10.3 o 10.4 prima di procedere alla versione 10.5.

[NOTE]
====
* Per i sistemi ASA r2, assicurarsi di eseguire l'aggiornamento agli ONTAP tools for VMware vSphere alla versione 10.5 e ONTAP alla versione 9.16.1, prima di configurare altre zone di disponibilità dello storage (SAZ).
* Se l'aggiornamento dagli ONTAP tools for VMware vSphere 10.3 o 10.4 alla versione 10.5 non riesce, non è possibile eseguire il rollback. Utilizzare un RPO basso o un ripristino snapshot per ripristinare la configurazione. Per gli ONTAP tools for VMware vSphere 10.2 e versioni precedenti, utilizzare zero-RPO per ripristinare la configurazione.


====
.Prima di iniziare
* Assicurarsi che il certificato del sistema ONTAP e i certificati vCenter integrati siano validi per almeno 5 giorni. Se i certificati scadono prima, l'aggiornamento fallisce.
* Per garantire un aggiornamento sicuro, verifica che i tuoi certificati includano voci Subject Alternative Name (SAN). Se i certificati non dispongono di voci SAN, impostare il flag di convalida del certificato su false per ignorare i controlli SAN durante l'aggiornamento.
* Assicurati di avere un quinto disco con una capacità di 100 GB su tutti i nodi.
* Verificare che la configurazione del nodo corrisponda alle specifiche riportate nella tabella seguente.


|===
| Tipo di implementazione | CPU (core) per nodo | Memoria (GB) per nodo | Spazio su disco (GB) per nodo | CPU totale (core) | Memoria (GB) | Spazio su disco totale (GB) 


| Non ha Small | 9 | 18 | 350 | 9 | 18 | 350 


| Terreno non ha | 13 | 26 | 350 | 13 | 26 | 350 


| HA piccolo | 9 | 18 | 350 | 27 | 54 | 1050 


| HA Media | 13 | 26 | 350 | 39 | 78 | 1050 


| HA grande | 17 | 34 | 350 | 51 | 102 | 1050 
|===
* Assicurarsi che il plug-in a caldo per CPU e RAM sia abilitato.
* Per gli ONTAP tools for VMware vSphere 10.3 o 10.4, eseguire uno snapshot inattivo sulla macchina virtuale degli strumenti ONTAP prima dell'aggiornamento.
* Abilita il backup con RPO basso e assicurati che un backup sia visibile nell'interfaccia di vCenter Client.


.Fasi
. Carica gli strumenti ONTAP per l'aggiornamento ISO di VMware vSphere nella libreria di contenuti.
. Nella pagina principale della macchina virtuale, selezionare *azioni* > *Modifica impostazioni*
. Selezionare il *file ISO della libreria di contenuti* nella finestra di modifica delle impostazioni sotto il campo *Unità CD/DVD*.
. Selezionare il file ISO, selezionare la casella *Connesso* per il campo *Unità CD/DVD* e fare clic su *OK*.
. Da vCenter Server, aprire una console agli strumenti ONTAP.
. Accedere come utente di manutenzione.
. Immettere *3* per selezionare il menu *Configurazione di sistema*.
. Immettere *7* per selezionare l'opzione *Aggiorna*.
+
Durante l'aggiornamento, se in uno qualsiasi dei certificati back-end di archiviazione integrati mancano le voci Subject Alternative Name (SAN), verrà visualizzato un messaggio che indica il SAN mancante.  Se si sceglie di procedere senza convalidare il SAN, l'aggiornamento continuerà, ma questa opzione non è consigliata a causa dei potenziali rischi per la sicurezza.

. Quando si esegue l'aggiornamento, le seguenti azioni vengono eseguite automaticamente:
+
.. Il certificato gateway viene rinnovato con un periodo di validità di 1 anno.  Quando si rimuove il precedente adattatore SRA e si carica il nuovo adattatore 10.5, la validità del certificato SRA passa da 10 anni a 1 anno.
.. Il plug-in remoto è stato aggiornato
.. I certificati ONTAP e vCenter Server vengono convalidati e aggiunti agli strumenti ONTAP
.. Il backup è abilitato




.Cosa succederà
Dopo l'aggiornamento agli ONTAP tools for VMware vSphere 10.5:

* Monitorare gli avvisi di sistema e pianificare il rinnovo del certificato del gateway prima che scada tra un anno.
* Rimuovere l'adattatore ONTAP Tools 10.4 o 10.3 SRA e caricare il file tar dell'adattatore 10.5 SRA.  Quindi, eseguire nuovamente la scansione degli adattatori SRA per aggiornare la pagina Adattatori VMware Site Recovery Storage Replication.


Dopo l'aggiornamento potrai:

* Disattivare i servizi dall'interfaccia utente di Manager
* Passaggio da un setup non ha a un setup ha
* È possibile espandere una configurazione non HA di piccole dimensioni a una configurazione non HA di medie dimensioni, oppure a una configurazione HA di medie o grandi dimensioni.


.Informazioni correlate
link:../migrate/migrate-to-latest-ontaptools.html["Migrazione dagli ONTAP tools for VMware vSphere 9.xx a 10.5"]
