---
permalink: migrate/migrate-to-latest-ontaptools.html 
sidebar: sidebar 
keywords: ONTAP tools migration, vVols migration, VMware vSphere, NFS datastores, VMFS datastores 
summary: Esegui la migrazione di ONTAP tools for VMware vSphere 9.xx alla versione 10.6 scegliendo un percorso in base al fatto che utilizzi o meno datastore vVols. 
---
= Migra dagli ONTAP tools for VMware vSphere 9.xx alla 10.6
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La migrazione da ONTAP tools for VMware vSphere 9.xx a 10.6 richiede passaggi diversi in base ai tipi di datastore.

Puoi migrare da ONTAP tools for VMware vSphere 9.12D1, 9.13D2 e 9.13P2 a ONTAP tools for VMware vSphere 10.6.

Se la tua configurazione ha datastore NFS e VMFS e nessun datastore vVols, disinstalla ONTAP tools 9.xx e distribuisci ONTAP tools 10.6. Se la tua configurazione contiene datastore vVols, migra il VASA Provider e l'SRA.

La tabella seguente descrive il processo di migrazione in questi due diversi scenari.

|===
| *Se la configurazione ha datastore vVols* | *Se la configurazione contiene solo datastore NFS e VMFS* 


| Passaggi: 1. link:../migrate/sra-vasa-migration.html["Migrare il provider VASA"] 2.  https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-policy-based-management-in-vsphere/creating-and-managing-vsphere-storage-policies.html["Creare policy di archiviazione VM"] | Passaggi: 1. Rimuovi ONTAP tools 9.xx dal tuo ambiente. Vedi  https://kb.netapp.com/data-mgmt/OTV/VSC_Kbs/OTV_How_to_remove_OTV_9_12_from_your_environment["Come rimuovere OTV 9.xx dal tuo ambiente"] nella NetApp Knowledge Base. 2. link:../deploy/quick-start.html["Distribuisci e configura ONTAP tools for VMware vSphere 10.6"] 3. link:../migrate/sra-vasa-migration.html["Aggiornare il SRA"] 4. https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-policy-based-management-in-vsphere/creating-and-managing-vsphere-storage-policies.html["Creare policy di archiviazione VM"] 
|===

NOTE: Dopo la migrazione da ONTAP tools for VMware vSphere 9.xx a 10.6, i datastore vVols che utilizzano il protocollo NVMe/FC diventano non operativi perché ONTAP tools 10.6 supporta il protocollo NVMe-oF solo con i datastore VMFS.



[[after-migration]]
== Dopo la migrazione

Verifica quanto segue:

* I datastore sono accessibili da vCenter Server.
* Le policy di storage delle VM sono mappate come previsto.
* Lo stato di protezione e replica risulta integro per i datastore configurati.

