---
permalink: deploy/ha-three-node-deployment.html 
sidebar: sidebar 
keywords:  
summary: È possibile configurare ha in configurazioni piccole, medie o grandi. 
---
= Implementazione della configurazione ha
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare tre nodi ha in configurazioni piccole, medie o grandi. L'implementazione HA utilizza Trident per memorizzare i dati dei servizi.

* I tre nodi ha di piccole dimensioni contengono 8 CPU e 16 GB di RAM per nodo.
* I tre nodi ha di medie dimensioni contengono 12 CPU e 24 GB di RAM per nodo.
* I tre nodi ad alta disponibilità di grandi dimensioni contengono 16 CPU e 32 GB di RAM per nodo.


*Prima di iniziare*

Questa attività offre istruzioni su come installare tre nodi ha in configurazioni piccole, medie o elevate.


NOTE: La creazione della libreria di contenuti è un passaggio obbligatorio per la distribuzione della configurazione ha a tre nodi. Fare riferimento alla link:../deploy/download-ontap-tools.html["Crea libreria di contenuti"] sezione per la procedura. Per ulteriori informazioni, consulta il https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html["Creazione e utilizzo della libreria di contenuti"] blog.

Assicurati di aver importato il tuo OVA nella tua libreria di contenuti. Tenere a portata di mano il nome della libreria dei contenuti e dell'elemento della libreria fornito all'elemento OVA.


NOTE: Prima di procedere con la distribuzione, impostare il DRS (Distributed Resource Scheduler) del cluster sull'inventario su 'Conservative' durante l'installazione degli strumenti ONTAP. In questo modo si garantisce che le VM non vengano migrate durante l'installazione.

*Fasi*

. Accedere al server vSphere.
. Passare al pool di risorse creato, al cluster o all'host in cui si desidera distribuire l'OVA.
. Fare clic con il pulsante destro del mouse sulla posizione desiderata e selezionare *Deploy OVF template...* (distribuire modello OVF...).
+

NOTE: Non implementare i tool ONTAP per la macchina virtuale VMware vSphere in un datastore vVol gestito dal reparto IT.

. Selezionare il file OVA tramite l'URL per il file _.ova_ o navigare alla cartella in cui è stato salvato il file _.ova_, quindi fare clic su *Avanti*.
. Per implementare i tool ONTAP per VMware vSphere dall'archivio di contenuti:
+
.. Vai alla tua libreria di contenuti e fai clic sull'elemento della libreria che desideri distribuire.
.. Fare clic su *azioni* > *Nuova VM da questo modello*


. Selezionare una risorsa di computer e fare clic su *Avanti*.
. Esaminare i dettagli del modello e fare clic su *Avanti*.
. Leggere e accettare il contratto di licenza e fare clic su *Avanti*.
. Selezionare la configurazione di distribuzione e fare clic su *Avanti*.
. Selezionare lo spazio di archiviazione per la configurazione e i file del disco e fare clic su *Avanti*.
. Selezionare la rete di destinazione per ciascuna rete di origine e fare clic su *Avanti*.
. Nella finestra *Personalizza modello*, compilare i campi obbligatori e fare clic su *Avanti*.
+
** Una volta abilitato l'ambito SVM, dovresti aver già abilitato il supporto SVM con l'indirizzo IP di gestione.
** Le informazioni qui fornite sono convalidate per i modelli corretti durante il processo di installazione. In caso di discrepanza, viene visualizzato un messaggio di errore sulla console Web e viene richiesto di correggere eventuali informazioni errate fornite.
** I nomi host devono essere costituiti da lettere maiuscole (A-Z), lettere minuscole (a-z), cifre (0-9) o dal trattino (-). Se si desidera configurare lo stack doppio, specificare il nome host mappato all'indirizzo IPv6.


. Rivedere i dettagli nella finestra *Pronto per il completamento*, selezionare *fine*.
+
Quando viene creata l'attività di distribuzione, l'avanzamento viene visualizzato nella barra delle applicazioni di vSphere.

. Accendere la macchina virtuale dopo il completamento dell'attività.
+
L'installazione viene avviata. È possibile tenere traccia dell'avanzamento dell'installazione nella console Web della VM. Come parte dell'installazione, le configurazioni dei nodi sono validate. Gli input forniti nelle diverse sezioni del modello Personalizza nel modulo OVF vengono convalidati. In caso di discrepanze, viene visualizzata una finestra di dialogo che richiede di intraprendere un'azione correttiva.

. Apportare le modifiche necessarie nella finestra di dialogo. Utilizzare il pulsante Tab per spostarsi all'interno del pannello e selezionare *OK*.
+
I valori forniti vengono nuovamente convalidati. Gli strumenti ONTAP per VMware vSphere consentono di correggere tre tentativi di valori non validi. Se dopo tre tentativi non è possibile risolvere i problemi, l'installazione del prodotto si interrompe e si consiglia di provare a eseguire l'installazione su una nuova VM.



Una volta completata l'installazione, la console Web mostra lo stato degli strumenti ONTAP per VMware vSphere.
