---
permalink: deploy/nonha-deployment.html 
sidebar: sidebar 
keywords:  
summary: È possibile configurare un singolo nodo non ha in configurazioni piccole o medie. 
---
= Implementa una configurazione non ha a nodo singolo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile implementare una configurazione a nodo singolo non ha in configurazioni piccole o medie.

* La configurazione piccola non ha contiene 8 CPU e 16 GB di RAM.
* La configurazione media non ha contiene 12 CPU e 24 GB di RAM.


*Prima di iniziare*

Assicurarsi che il percorso di rete sia presente. La rete di dati dello storage deve essere accessibile dalla rete di gestione delle macchine virtuali. Ad esempio, accedere a ONTAP > eseguire il comando _network route create -vserver <SVM> -destination 0,0.0.0/0 -gateway <gateway_ip>_

*Fasi*

. Accedere al server vSphere.
. Passare al pool di risorse creato, al cluster o all'host in cui si desidera distribuire l'OVA.
. Fare clic con il pulsante destro del mouse sulla posizione desiderata e selezionare *Deploy OVF template...* (distribuire modello OVF...).
+

NOTE: Non implementare i tool ONTAP per la macchina virtuale VMware vSphere in un datastore vVol gestito dal reparto IT.

. Selezionare il file OVA tramite l'URL per il file _.ova_ o navigare alla cartella in cui è stato salvato il file _.ova_, quindi fare clic su *Avanti*.
. Selezionare una risorsa di computer e fare clic su *Avanti*.
. Esaminare i dettagli del modello e fare clic su *Avanti*.
. Leggere e accettare il contratto di licenza.
. Selezionare la configurazione di distribuzione e fare clic su *Avanti*.
+
Le opzioni di implementazione avanzate utilizzano Trident come provisioner di storage dinamico per ONTAP per creare volumi e la semplice implementazione usa lo storage locale per creare volumi.

. Selezionare lo spazio di archiviazione per la configurazione e i file del disco e fare clic su *Avanti*.
. Selezionare la rete di destinazione per ciascuna rete di origine e fare clic su *Avanti*.
. Nel modello *Personalizza*, immettere i dettagli richiesti e fare clic su *Avanti*
+
** Una volta abilitato l'ambito SVM, dovresti aver già abilitato il supporto SVM con l'indirizzo IP di gestione.
** Le informazioni qui fornite sono convalidate per i modelli corretti durante il processo di installazione. In caso di discrepanza, viene visualizzato un messaggio di errore sulla console Web e viene richiesto di correggere eventuali informazioni errate fornite.
** I nomi host devono essere costituiti da lettere maiuscole (A-Z), lettere minuscole (a-z), cifre (0-9) o dal trattino (-). Se si desidera configurare lo stack doppio, specificare il nome host mappato all'indirizzo IPv6.


. Rivedere i dettagli nella finestra *Pronto per il completamento*, selezionare *fine*.
+
Quando viene creata l'attività di distribuzione, l'avanzamento viene visualizzato nella barra delle applicazioni di vSphere.

. Accendere la macchina virtuale dopo il completamento dell'attività.
+
L'installazione viene avviata. È possibile tenere traccia dell'avanzamento dell'installazione nella console Web della VM. Come parte dell'installazione, le configurazioni dei nodi sono validate. Gli input forniti nelle diverse sezioni del modello Personalizza nel modulo OVF vengono convalidati. In caso di discrepanze, viene visualizzata una finestra di dialogo che richiede di intraprendere un'azione correttiva.

. Apportare le modifiche necessarie nella finestra di dialogo. Utilizzare il pulsante Tab per spostarsi all'interno del pannello e selezionare *OK*.
+
I valori forniti vengono nuovamente convalidati. Gli strumenti ONTAP per VMware vSphere consentono di correggere tre tentativi di valori non validi. Se dopo tre tentativi non è possibile risolvere i problemi, l'installazione del prodotto si interrompe e si consiglia di provare a eseguire l'installazione su una nuova VM.



Una volta completata l'installazione, la console Web mostra lo stato degli strumenti ONTAP per VMware vSphere.
