---
permalink: deploy/ontap-tools-deployment.html 
sidebar: sidebar 
keywords:  
summary: 'I tool ONTAP per l"appliance VMware vSphere sono sempre implementati come nodo singolo di piccole dimensioni con servizi core per supportare i datastore NFS/VMFS.' 
---
= Implementa i tool ONTAP per VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I tool ONTAP per l'appliance VMware vSphere sono sempre implementati come nodo singolo di piccole dimensioni con servizi core per supportare i datastore NFS/VMFS.

*Prima di iniziare*

Una libreria di contenuti in VMware è un oggetto contenitore che memorizza modelli di VM, modelli di vApp e altri tipi di file. La distribuzione con la libreria di contenuti offre un'esperienza senza problemi poiché non dipende dalla connettività di rete.


NOTE: È necessario archiviare la libreria di contenuti in un datastore condiviso, in modo che tutti gli host di un cluster possano accedervi. È necessario creare una libreria di contenuti per memorizzare l'OVA prima di modificare le impostazioni dell'appliance in configurazione ha. Il modello della libreria di contenuti una volta caricato non deve essere eliminato dopo la distribuzione.


NOTE: Per consentire in un secondo momento l'implementazione ha, la macchina virtuale che ospita gli strumenti ONTAP non deve essere implementata direttamente su un host ESXi. Ma deve essere implementata in un cluster o in un pool di risorse.

Se non si dispone già di una libreria di contenuti adatta, crearne una utilizzando i seguenti passaggi:


NOTE: Se si intende utilizzare solo una distribuzione con un singolo nodo di piccole dimensioni, non è necessario creare una libreria di contenuti.

. Scaricare il `.zip` file contenente i file binari (_.ova_) e i certificati firmati per gli strumenti ONTAP per VMware vSphere dal https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Sito di supporto NetApp"^] .
. Accedere al client vSphere utilizzando `\https://<vcenterip>/<ui>`
. Selezionare i puntini di sospensione orizzontali accanto al client vSphere e selezionare *Libreria di contenuti*.
. Selezionare *Crea* a destra della pagina.
. Fornire un nome per la libreria e creare la libreria di contenuti.
. Accedere alla libreria di contenuti creata.
. Selezionare *azioni* nella parte destra della pagina e selezionare *Importa elemento* e importare il file OVA.



NOTE: Per ulteriori informazioni, consulta il https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html["Creazione e utilizzo della libreria di contenuti"] blog.

Assicurarsi di aver importato l'OVA nella libreria di contenuti.


NOTE: Prima di procedere con la distribuzione, impostare il DRS (Distributed Resource Scheduler) del cluster sull'inventario su 'Conservative' durante l'installazione degli strumenti ONTAP. In questo modo si garantisce che le VM non vengano migrate durante l'installazione.

.Fasi
. Scaricare il `.zip` file contenente i file binari (_.ova_) e i certificati firmati per gli strumenti ONTAP per VMware vSphere dal https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Sito di supporto NetApp"^] . Se l'OVA è stato importato nella libreria di contenuti, è possibile saltare questo passaggio e procedere con il passaggio successivo in quanto è possibile eseguire la distribuzione direttamente dalla libreria di contenuti.
. Accedere al server vSphere.
. Passare al pool di risorse creato, al cluster o all'host in cui si desidera distribuire l'OVA.
. Fare clic con il pulsante destro del mouse sulla posizione desiderata e selezionare *Deploy OVF template...* (distribuire modello OVF...).
+

NOTE: Non memorizzare mai tool ONTAP per macchine virtuali VMware vSphere su datastore vVol gestiti.

. Selezionare il file OVA tramite l'URL per il file _.ova_ oppure selezionare la cartella in cui è stato salvato il file _.ova_, quindi selezionare *Avanti*.
. Per implementare i tool ONTAP per VMware vSphere dall'archivio di contenuti:
+
.. Vai alla tua libreria di contenuti e seleziona l'elemento della libreria che desideri distribuire.
.. Selezionare *azioni* > *Nuova VM da questo modello*


. Nella finestra *Select a name and folder* for the virtual machine (Seleziona un nome e una cartella* per la macchina virtuale), immettere il nome della macchina virtuale e selezionare la posizione per la macchina virtuale. Se si seleziona la casella di controllo *Personalizza l'hardware di questa macchina virtuale*, viene attivata una procedura chiamata *Personalizza hardware* prima di raggiungere la finestra *Pronto per il completamento*.
. Selezionare una risorsa di computer e selezionare *Avanti*. Puoi scegliere di selezionare la casella di controllo per *accendere automaticamente la VM distribuita*.
. Esaminare i dettagli del modello e selezionare *Avanti*.
. Leggere e accettare il contratto di licenza e selezionare *Avanti*.
. Selezionare lo spazio di archiviazione per la configurazione e i file del disco e selezionare *Avanti*.
. Selezionare la rete di destinazione per ciascuna rete di origine e selezionare *Avanti*.
. Nella finestra *Personalizza modello*, compilare i campi obbligatori e selezionare *Avanti*.
+
** Le informazioni qui fornite sono convalidate per i modelli corretti durante il processo di installazione. In caso di discrepanza, viene visualizzato un messaggio di errore sulla console Web e viene richiesto di correggere eventuali informazioni errate fornite.
** I nomi host devono essere costituiti da lettere maiuscole (A-Z), lettere minuscole (a-z), cifre (0-9) o dal trattino (-). Se si desidera configurare lo stack doppio, specificare il nome host mappato all'indirizzo IPv6.
+

NOTE: Pure IPv6 non è supportato. La modalità mista è supportata con VLAN con indirizzi IPv6 e IPv4.



. Nella finestra *Customize hardware* (Personalizza hardware*) si dovrebbe abilitare l'aggiunta a caldo della CPU e l'hot plug della memoria.
. Rivedere i dettagli nella finestra *Pronto per il completamento*, selezionare *fine*.
+
Quando viene creata l'attività di distribuzione, l'avanzamento viene visualizzato nella barra delle applicazioni di vSphere.

. Accendere la macchina virtuale dopo il completamento dell'attività.
+

NOTE: Prima di accendere la macchina virtuale, assicurarsi che gli hot plug-in siano abilitati sia per la CPU che per la memoria.



È possibile tenere traccia dell'avanzamento dell'installazione nella console Web della VM.

In caso di discrepanze nei valori immessi nel modulo OVF, viene visualizzata una finestra di dialogo che richiede di intraprendere un'azione correttiva. Apportare le modifiche necessarie all'interno della finestra di dialogo, utilizzando il pulsante Tab per navigare e selezionare "OK". Hai tre tentativi per risolvere eventuali problemi. Se i problemi persistono dopo tre tentativi, il processo di installazione verrà interrotto e si consiglia di riprovare l'installazione su una nuova VM.
