---
permalink: deploy/prerequisites.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: Prima di implementare gli strumenti ONTAP per VMware vSphere, è necessario conoscere i requisiti di spazio per il pacchetto di implementazione e alcuni requisiti di base del sistema host. 
---
= Strumenti ONTAP per requisiti e limiti di configurazione VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di implementare gli strumenti ONTAP per VMware vSphere, è necessario conoscere i requisiti di spazio per il pacchetto di implementazione e alcuni requisiti di base del sistema host.

Puoi utilizzare tool ONTAP per VMware vSphere con VMware vCenter Server Virtual Appliance (vCSA). È necessario implementare i tool ONTAP per VMware vSphere su un client vSphere supportato che include il sistema ESXi.



== Requisiti di sistema

* *Requisiti di spazio per il pacchetto di installazione per nodo*
+
** 15 GB per le installazioni con thin provisioning
** 348 GB per installazioni con thick provisioning


* *Requisiti di dimensionamento del sistema host* La tabella seguente mostra la memoria consigliata per ogni dimensione di distribuzione. Per le distribuzioni ad alta disponibilità (HA), è necessaria una dimensione dell'appliance tre volte superiore a quella indicata.


|===


| *Tipo di distribuzione* | *CPU per nodo* | *Memoria (GB) per nodo* | *Spazio su disco (GB) con thick provisioning per nodo* 


| Piccolo | 9 | 18 | 350 


| Medio | 13 | 26 | 350 


| NOTA BENE: L'implementazione estesa è solo per la configurazione ha. | 17 | 34 | 350 
|===

NOTE: Una volta abilitato il backup, ogni cluster di tool ONTAP necessita di altri 50GB di spazio nel datastore in cui vengono implementate le macchine virtuali. Pertanto, una piattaforma non ha richiede 400 GB e ha richiede 1100 GB di spazio in totale.



== Requisiti minimi di archiviazione e applicazione

|===
| Storage, host e applicazioni | Requisiti di versione 


| ONTAP | 9.15.1, 9.16.0, 9.16.1, 9.17.0 e 9.17.1 


| Gli strumenti ONTAP supportavano gli host ESXi | da 7.0.3 in poi 


| Gli strumenti ONTAP supportavano vCenter Server | Da 7.0U3 


| Provider VASA | 3,0 


| Applicazione OVA | 10,5 


| Host ESXi per implementare la macchina virtuale degli strumenti ONTAP | 7.0U3 e 8.0U3 


| VCenter Server per implementare la macchina virtuale degli strumenti ONTAP | 7.0 e 8.0 
|===

NOTE: A partire dai tool ONTAP per VMware vSphere 10,4, l'hardware della macchina virtuale viene modificato dalla versione 10 alla 17.

L'Interoperability Matrix Tool (IMT) contiene le informazioni più recenti sulle versioni supportate di ONTAP, vCenter Server, gli host ESXi e le applicazioni plug-in.

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Tool di matrice di interoperabilità"^]



== Requisiti delle porte

La tabella seguente illustra le porte di rete utilizzate da NetApp e le relative funzioni. Esistono tre diversi tipi di porte:

* Porte esterne: queste porte sono accessibili dall'esterno del cluster o del nodo Kubernetes. Consentono ai servizi di comunicare con reti o utenti esterni, consentendo l'integrazione con sistemi esterni all'ambiente cluster.
* Porte inter-nodo: queste porte consentono la comunicazione tra i nodi all'interno del cluster Kubernetes. Sono necessari per attività di clustering come la condivisione di dati e la collaborazione. Per le distribuzioni a nodo singolo, le porte tra nodi vengono utilizzate solo all'interno del nodo e non necessitano di accesso esterno. Le porte internodo possono accettare traffico dall'esterno del cluster. Bloccare l'accesso a Internet alle porte tra nodi tramite regole firewall.
* Porte interne: queste porte comunicano all'interno del cluster Kubernetes utilizzando indirizzi ClusterIP. Non sono esposti esternamente e non devono essere aggiunti alle regole del firewall.



NOTE: Assicurarsi che tutti i nodi degli strumenti ONTAP risiedano nella stessa subnet per mantenere una comunicazione ininterrotta tra loro.

Fare clic per espandere o comprimere la tabella dei requisiti delle porte.

[%collapsible]
====
|===
| *Nome del servizio/componente* | *Porta* | *Protocollo* | *Tipo di porta* | *Descrizione* 


| ntv-gateway-svc (LB) | 443, 8443 | TCP | Esterno | Porta di passaggio per le comunicazioni in entrata per il servizio VASA Provider. Il certificato autofirmato del provider VASA e il certificato CA personalizzato sono ospitati su questa porta. 


| SSH | 22 | TCP | Esterno | Secure Shell per l'accesso remoto al server e l'esecuzione dei comandi. 


| server rke2 | 9345 | TCP | Inter-nodo | API del supervisore RKE2 (limita alle reti attendibili). 


| kube-apiserver | 6443 | TCP | Inter-nodo | Porta del server API Kubernetes (limita alle reti attendibili). 


| rpcbind/portmapper | 111 | TCP/UDP | Inter-nodo | Utilizzato per la comunicazione RPC tra servizi. 


| coredns (DNS) | 53 | TCP/UDP | Inter-nodo | Servizio Domain Name System (DNS) per la risoluzione dei nomi all'interno del cluster. 


| NTP | 123 | UDP | Inter-nodo | Network Time Protocol (NTP) per la sincronizzazione dell'ora. 


| ecc. | 2379, 2380, 2381 | TCP | Inter-nodo | Archivio chiave-valore per i dati del cluster. 


| kube-vip | 2112 | TCP | Inter-nodo | Porta del server API Kubernetes. 


| kubelet | 10248, 10250 | TCP | Inter-nodo | Componente Kubernetes 


| kube-controller | 10257 | TCP | Inter-nodo | Componente Kubernetes 


| cloud controller | 10258 | TCP | Inter-nodo | Componente Kubernetes 


| kube-scheduler | 10259 | TCP | Inter-nodo | Componente Kubernetes 


| kube-proxy | 10249, 10256 | TCP | Inter-nodo | Componente Kubernetes 


| nodo calico | 9091, 9099 | TCP | Inter-nodo | Componente di rete Calico. 


| contenitore | 10010 | TCP | Inter-nodo | Servizio demone del contenitore. 


| VXLAN (flanella) | 8472 | UDP | Inter-nodo | Rete di sovrapposizione per la comunicazione tra pod. 
|===

NOTE: Per le distribuzioni HA, assicurarsi che la porta UDP 8472 sia aperta tra tutti i nodi. Questa porta consente la comunicazione pod-to-pod tra i nodi; bloccandola si interromperà la rete tra nodi.

====


== Limiti di configurazione per l'implementazione dei tool ONTAP per VMware vSphere

La seguente tabella illustra la configurazione dei tool ONTAP per VMware vSphere.

|===


| *Implementazione* | *Tipo* | *Numero di vVol* | *Numero di host* 


| Non ha | Piccolo (S) | CIRCA 12K MB | 32 


| Non ha | Medio (M) | CIRCA 24K MB | 64 


| Alta disponibilità | Piccolo (S) | CIRCA 24K MB | 64 


| Alta disponibilità | Medio (M) | circa 50k mb | 128 


| Alta disponibilità | Grande (L) | circa 100k mb | 256 [NOTA] I conteggi degli host nella tabella rappresentano il totale combinato di tutti i vCenter connessi. 
|===


== Tool ONTAP per VMware vSphere - Storage Replication Adapter (SRA)

La tabella seguente mostra i numeri supportati per istanza di VMware Live Site Recovery utilizzando gli strumenti ONTAP per VMware vSphere.

|===
| *Dimensione della distribuzione vCenter* | *Piccolo* | *Medio* 


| Numero totale di macchine virtuali configurate per la protezione mediante replica basata su array | 2000 | 5000 


| Numero totale di gruppi di protezione da replica basati su array | 250 | 250 


| Numero totale di gruppi di protezione per piano di ripristino | 50 | 50 


| Numero di datastore replicati | 255 | 255 


| Numero di macchine virtuali | 4000 | 7000 
|===
La tabella seguente mostra il numero di VMware Live Site Recovery e i corrispondenti strumenti ONTAP per le dimensioni della distribuzione di VMware vSphere.

|===


| *Numero di istanze di VMware Live Site Recovery* | *Dimensioni di distribuzione degli strumenti ONTAP* 


| Fino a 4 | Piccolo 


| da 4 a 8 | Medio 


| Più di 8 | Grande 
|===
Per ulteriori informazioni, fare riferimento a https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/overview/site-recovery-manager-system-requirements/operational-limits-of-site-recovery-manager.html["Limiti operativi di VMware Live Site Recovery"].
