---
permalink: deploy/prerequisites.html 
sidebar: sidebar 
keywords: ONTAP tools requirements, configuration limits, supported versions, sizing 
summary: Verifica le versioni supportate, il dimensionamento, i requisiti delle porte e i limiti di configurazione prima di implementare ONTAP tools for VMware vSphere. 
---
= Strumenti ONTAP per requisiti e limiti di configurazione VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verifica le versioni supportate, il dimensionamento, i requisiti delle porte e i limiti di configurazione prima di implementare ONTAP tools for VMware vSphere.

Distribuisci ONTAP tools for VMware vSphere in un ambiente vSphere supportato che include host ESXi e VMware vCenter Server Virtual Appliance (vCSA).



[[system-requirements]]
== Requisiti di sistema

* *Requisiti di spazio per il pacchetto di installazione per nodo*
+
** 15 GB per le installazioni con thin provisioning
** 348 GB per installazioni con thick provisioning


* *Requisiti di dimensionamento del sistema host* La tabella seguente mostra la CPU, la memoria e lo spazio su disco consigliati per nodo per ogni dimensione di implementazione. Per le implementazioni ad alta disponibilità (HA), distribuisci tre nodi.


|===


| *Tipo di distribuzione* | *CPU per nodo* | *Memoria (GB) per nodo* | *Spazio su disco (GB) con thick provisioning per nodo* 


| Extra piccola (XS) | 6 | 12 | 350 


| Piccolo | 9 | 18 | 350 


| Medio | 13 | 26 | 350 


| Grande | 17 | 34 | 350 
|===

NOTE: Le implementazioni di grandi dimensioni sono supportate solo per la configurazione HA.


NOTE: Quando il backup è abilitato, ogni cluster ONTAP tools necessita di ulteriori 50 GB di spazio sul datastore in cui sono distribuite le VM. Pertanto, la configurazione non HA richiede 400 GB e la configurazione HA richiede 1100 GB di spazio in totale.



[[minimum-storage-and-application-requirements]]
== Requisiti minimi di archiviazione e applicazione

|===
| Storage, host e applicazioni | Requisiti di versione 


| Sistemi ONTAP | 9.16.1, 9.17.1, 9.18.1, 9.19.1 


| Host ESXi gestiti da ONTAP tools | da 7.0.3 in poi 


| vCenter Server gestiti da ONTAP tools | Dalla versione 8.0U3 in poi 


| Provider VASA | 3,0 


| Applicazione OVA | 10,6 


| Host ESXi utilizzato per distribuire la macchina virtuale ONTAP tools | 7.0U3 e 8.0U3 


| vCenter Server utilizzato per distribuire la macchina virtuale ONTAP tools | 7.0 e 8.0 
|===

NOTE: A partire da ONTAP tools for VMware vSphere 10.4, la versione hardware della macchina virtuale cambia da 10 a 17.

L'Interoperability Matrix Tool (IMT) contiene le informazioni più recenti sulle versioni supportate di ONTAP, vCenter Server, gli host ESXi e le applicazioni plug-in.

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Tool di matrice di interoperabilità"^]



[[port-requirements]]
== Requisiti delle porte

La tabella seguente illustra le porte di rete utilizzate da NetApp e le relative funzioni. Esistono tre diversi tipi di porte:

* Porte esterne: queste porte sono accessibili dall'esterno del cluster o del nodo Kubernetes. Consentono ai servizi di comunicare con reti o utenti esterni, consentendo l'integrazione con sistemi esterni all'ambiente cluster.
* Porte inter-nodo: queste porte consentono la comunicazione tra i nodi all'interno del cluster Kubernetes. Sono necessarie per le operazioni del cluster, come lo scambio di dati e il coordinamento dei nodi. Nelle implementazioni a nodo singolo, le porte inter-nodo vengono utilizzate solo all'interno del nodo e non richiedono accesso esterno. Consenti il traffico inter-nodo solo dalle reti del cluster attendibili e blocca l'accesso a Internet tramite regole firewall.
* Porte interne: queste porte comunicano all'interno del cluster Kubernetes utilizzando indirizzi ClusterIP. Non sono esposti esternamente e non devono essere aggiunti alle regole del firewall.



NOTE: Assicurarsi che tutti i nodi degli strumenti ONTAP risiedano nella stessa subnet per mantenere una comunicazione ininterrotta tra loro.

Fare clic per espandere o comprimere la tabella dei requisiti delle porte.

[%collapsible]
====
|===
| *Nome del servizio/componente* | *Porta* | *Protocollo* | *Tipo di porta* | *Descrizione* 


| ntv-gateway-svc (LB) | 443, 8443 | TCP | Esterno | Porta di passaggio per le comunicazioni in entrata per il servizio VASA Provider. Il certificato autofirmato del provider VASA e il certificato CA personalizzato sono ospitati su questa porta. 


| SSH | 22 | TCP | Esterno | Secure Shell per l'accesso remoto al server e l'esecuzione dei comandi. 


| server rke2 | 9345 | TCP | Inter-nodo | API del supervisore RKE2 (limita alle reti attendibili). 


| kube-apiserver | 6443 | TCP | Inter-nodo | Porta del server API Kubernetes (limita alle reti attendibili). 


| rpcbind/portmapper | 111 | TCP/UDP | Inter-nodo | Utilizzato per la comunicazione RPC tra servizi. 


| coredns (DNS) | 53 | TCP/UDP | Inter-nodo | Servizio Domain Name System (DNS) per la risoluzione dei nomi all'interno del cluster. 


| NTP | 123 | UDP | Inter-nodo | Network Time Protocol (NTP) per la sincronizzazione dell'ora. 


| ecc. | 2379, 2380, 2381 | TCP | Inter-nodo | Archivio chiave-valore per i dati del cluster. 


| kube-vip | 2112 | TCP | Inter-nodo | Porta del server API Kubernetes. 


| kubelet | 10248, 10250 | TCP | Inter-nodo | Componente Kubernetes 


| kube-controller | 10257 | TCP | Inter-nodo | Componente Kubernetes 


| cloud controller | 10258 | TCP | Inter-nodo | Componente Kubernetes 


| kube-scheduler | 10259 | TCP | Inter-nodo | Componente Kubernetes 


| kube-proxy | 10249, 10256 | TCP | Inter-nodo | Componente Kubernetes 


| nodo calico | 9091, 9099 | TCP | Inter-nodo | Componente di rete Calico. 


| contenitore | 10010 | TCP | Inter-nodo | Servizio demone del contenitore. 


| VXLAN (flanella) | 8472 | UDP | Inter-nodo | Rete di sovrapposizione per la comunicazione tra pod. 
|===

NOTE: Per le distribuzioni HA, assicurarsi che la porta UDP 8472 sia aperta tra tutti i nodi. Questa porta consente la comunicazione pod-to-pod tra i nodi; bloccandola si interromperà la rete tra nodi.

====


[[configuration-limits-for-vvol-datastores]]
== Limiti di configurazione per i datastore vVol

Usa la tabella seguente come guida per configurare ONTAP tools for VMware vSphere.

|===


| *Implementazione* | *Tipo* | *Numero di vVol* | *Numero di host* 


| Non ha | Piccolo (S) | fino a 12K | 32 


| Non ha | Medio (M) | fino a 24K | 64 


| HA | Piccolo (S) | fino a 24K | 64 


| HA | Medio (M) | fino a 50K | 128 


| HA | Grande (L) | fino a 100K | 256 
|===

NOTE: I conteggi degli host nella tabella rappresentano il totale combinato tra tutti i vCenters connessi.



[[configuration-limits-for-vmfs-and-nfs-datastores]]
== Limiti di configurazione per i datastore VMFS e NFS

I limiti di configurazione elencati in questa sezione sono convalidati e supportati da NetApp. I limiti effettivi possono variare a seconda dell'ambiente e del carico di lavoro. Il superamento di questi limiti può influire sulle prestazioni o sul supporto e non è consigliato. Considerare quanto segue quando si esamina la tabella:

* Il Disaster Recovery (DR) delle macchine virtuali è configurato utilizzando criteri sincroni, asincroni o di sincronizzazione rigorosa. Il DR non è supportato per il protocollo NVMe.
* La protezione del cluster host ESXi utilizza SnapMirror Active Sync, che non supporta distribuzioni multi-vCenter.
* ONTAP tools limita solo il numero di host ESXi e datastore in base alle dimensioni dell'implementazione. Non ci sono restrizioni sul numero di vCenter Server che possono essere connessi a ONTAP tools.
* ONTAP tools esegue il discovery parallelo di tutti gli oggetti di storage. I limiti di configurazione per gli oggetti di storage ONTAP si applicano indipendentemente dal numero di oggetti attivamente in uso.
* ONTAP tools non impone un limite al numero di vCenter Servers che possono essere integrati. I limiti di configurazione sono determinati dal numero di host e datastore supportati, come dettagliato nella tabella seguente.


|===
| Distribuzione | Numero di datastore VMFS e NFS | Numero di datastore VMFS con DR abilitato | Numero di host 


| Extra piccola | 50 | 50 | 16 


| Non ha Small | 200 | 80 | 32 


| Terreno non ha | 250 | 100 | 32 


| HA Extra small | 200 | 100 | 32 


| HA piccolo | 350 | 200 | 64 


| HA Media | 600 | 200 | 128 


| HA grande | 1024 | 250 | 256 
|===


[[ontap-tools-for-vmware-vsphere-storage-replication-adapter-sra]]
== Tool ONTAP per VMware vSphere - Storage Replication Adapter (SRA)

La tabella seguente mostra i numeri supportati per istanza di VMware Live Site Recovery utilizzando gli strumenti ONTAP per VMware vSphere.

|===
| *vCenter dimensioni di implementazione* | *Piccolo* | *Medio* 


| Numero totale di macchine virtuali configurate per la protezione mediante replica basata su array | 2000 | 5000 


| Numero totale di gruppi di protezione da replica basati su array | 250 | 250 


| Numero totale di gruppi di protezione per piano di ripristino | 50 | 50 


| Numero di datastore replicati | 255 | 255 


| Numero di macchine virtuali | 4000 | 7000 
|===
La tabella seguente mostra il numero di istanze di VMware Live Site Recovery e la corrispondente dimensione di implementazione di ONTAP tools for VMware vSphere.

|===


| *Numero di istanze di VMware Live Site Recovery* | *Dimensioni di implementazione di ONTAP tools* 


| Fino a 4 | Piccolo 


| da 4 a 8 | Medio 


| Più di 8 | Grande 
|===
Per ulteriori informazioni, fare riferimento a https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/overview/site-recovery-manager-system-requirements/operational-limits-of-site-recovery-manager.html["Limiti operativi di VMware Live Site Recovery"].
