---
section: deploy
title: Implementa i tool ONTAP per VMware vSphere
entries:
- title: Avvio rapido dei tool ONTAP per VMware vSphere
  url: "/deploy/quick-start.html"
- title: Workflow di implementazione ha (High Availability, alta disponibilità)
  url: "/deploy/ha-workflow.html"
- title: Requisiti e limiti di configurazione degli strumenti ONTAP
  url: "/deploy/prerequisites.html"
- title: Prima di iniziare
  url: "/deploy/pre-deploy-checks.html"
- title: Implementa i tool ONTAP per VMware vSphere
  url: "/deploy/ontap-tools-deployment.html"
- title: Risolvere gli errori di distribuzione
  url: "/deploy/deployment-error-codes.html"
