---
permalink: protect/configure-storage-replication-adapter-for-highly-scaled-environment.html 
sidebar: sidebar 
keywords:  
summary: 'È necessario configurare gli intervalli di timeout della memoria in base alle impostazioni consigliate per l"adattatore di replica della memoria di massa \(SRA\) in modo che funzionino in modo ottimale in ambienti altamente scalabili.' 
---
= Configurare SRA per ambienti ad elevata scalabilità
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario configurare gli intervalli di timeout dello storage in base alle impostazioni consigliate per Storage Replication Adapter (SRA) in modo da garantire prestazioni ottimali in ambienti altamente scalabili.



== Impostazioni del provider di storage

Impostare i seguenti valori di timeout su SRM per l'ambiente in scala:

|===


| *Impostazioni avanzate* | *Valori di timeout* 


 a| 
`StorageProvider.resignatureTimeout`
 a| 
Aumentare il valore dell'impostazione da 900 secondi a 12000 secondi.



 a| 
`storageProvider.hostRescanDelaySec`
 a| 
60



 a| 
`storageProvider.hostRescanRepeatCnt`
 a| 
20



 a| 
`storageProvider.hostRescanTimeoutSec`
 a| 
Impostare un valore alto (ad esempio: 99999)

|===
Attivare anche il `StorageProvider.autoResignatureMode` opzione.

Per ulteriori informazioni sulla modifica delle impostazioni dello Storage Provider, consultare la documentazione di VMware.

https://docs.vmware.com/en/Site-Recovery-Manager/8.7/com.vmware.srm.admin.doc/GUID-E4060824-E3C2-4869-BC39-76E88E2FF9A0.html["Documentazione VMware vSphere: Modifica delle impostazioni dello Storage Provider"]



== Impostazioni di storage

Quando si preme un timeout, aumentare i valori di `storage.commandTimeout` e. `storage.maxConcurrentCommandCnt` ad un valore più alto.


NOTE: L'intervallo di timeout specificato è il valore massimo. Non è necessario attendere il raggiungimento del timeout massimo. La maggior parte dei comandi termina entro l'intervallo di timeout massimo impostato.

La documentazione VMware sulla modifica delle impostazioni DEL provider SAN contiene ulteriori informazioni.

https://docs.vmware.com/en/Site-Recovery-Manager/8.7/com.vmware.srm.admin.doc/GUID-711FD223-50DB-414C-A2A7-3BEB8FAFDBD9.html["Documentazione di VMware Site Recovery Manager: Modifica delle impostazioni di storage"]
