---
permalink: protect/configure-protection-groups.html 
sidebar: sidebar 
keywords:  
summary: È necessario creare gruppi di protezione per proteggere un gruppo di macchine virtuali sul sito protetto. 
---
= Configurare i gruppi di protezione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario creare gruppi di protezione per proteggere un gruppo di macchine virtuali sul sito protetto.

*Cosa ti serve*

Assicurarsi che i siti di origine e di destinazione siano configurati per:

* È installata la stessa versione di VMware Live Site Recovery
* Macchine virtuali
* Siti di ripristino e protezione associati
* Gli archivi dati di origine e di destinazione devono essere montati sui rispettivi siti


*Fasi*

. Accedere a vCenter Server e selezionare *Site Recovery* > *Protection Groups*.
. Nel riquadro *gruppi di protezione*, selezionare *nuovo*.
. Specificare un nome e una descrizione per il gruppo protezione, direzione e selezionare *Avanti*.
. Nel campo *Type*, selezionare l'opzione *Type Field...* come gruppi di datastore (replica basata su array) per NFS e datastore VMFS.
Il dominio degli errori non è altro che SVM con replica abilitata. Vengono visualizzate le SVM che hanno implementato solo il peering e che non hanno problemi.
. Nella scheda gruppi di replica, selezionare la coppia di array abilitata o i gruppi di replica che hanno configurato la macchina virtuale, quindi selezionare *Avanti*.
+
Tutte le macchine virtuali presenti nel gruppo di replica vengono aggiunte al gruppo di protezione.

. Selezionare il piano di ripristino esistente o crearne uno nuovo selezionando *Aggiungi al nuovo piano di ripristino*.
. Nella scheda Pronto per il completamento, esaminare i dettagli del gruppo di protezione creato, quindi selezionare *fine*.

