---
permalink: protect/configure-protection-groups.html 
sidebar: sidebar 
keywords:  
summary: È necessario creare gruppi di protezione per proteggere un gruppo di macchine virtuali sul sito protetto. 
---
= Configurare siti protetti e di ripristino
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario creare gruppi di protezione per proteggere un gruppo di macchine virtuali sul sito protetto.

Quando si aggiunge un nuovo datastore, è possibile includerlo nel gruppo di datastore esistente oppure aggiungere un nuovo datastore e creare un nuovo volume o gruppo di coerenza per la protezione. Dopo aver aggiunto un nuovo datastore a un gruppo di coerenza o volume protetto, aggiornare SnapMirror ed eseguire il discovery dello storage sia sul sito protetto che su quello di ripristino. È possibile eseguire il discovery manualmente o in base a una pianificazione per garantire che il nuovo datastore venga rilevato e protetto.



== Associare siti protetti e di ripristino

È necessario associare i siti protetti e di ripristino creati utilizzando il client vSphere per consentire l'individuazione dei sistemi di storage mediante Storage Replication Adapter (SRA).


NOTE: Storage Replication Adapter (SRA) supporta il fan-out con una relazione di sincronizzazione di tipo Automated Failover Duplex e una relazione asincrona SnapMirror sul gruppo di coerenza. Tuttavia, la fan-out con due SnapMirror asincroni sul gruppo di coerenza o gli SnapMirror fan-out sul volume non sono supportati.

.Prima di iniziare
* È necessario che VMware Live Site Recovery sia installato sui siti protetti e di ripristino.
* È necessario che SRA sia installato nei siti protetti e di ripristino.


.Fasi
. Nella home page di vSphere Client, fare doppio clic sull'icona *Site Recovery* e quindi selezionare *Siti*.
. Selezionare *oggetti* > *azioni* > *abbina siti*.
. Nella finestra di dialogo *Associa server di Site Recovery Manager*, immettere l'indirizzo del Platform Services Controller del sito protetto, quindi selezionare *Avanti*.
. Nella sezione Select vCenter Server (Seleziona server vCenter), procedere come segue:
+
.. Verificare che vCenter Server del sito protetto venga visualizzato come candidato corrispondente per l'associazione.
.. Immettere le credenziali amministrative SSO, quindi selezionare *fine*.


. Se richiesto, selezionare *Sì* per accettare i certificati di protezione.


.Risultato
Nella finestra di dialogo *Oggetti* vengono visualizzati sia i siti protetti che quelli di ripristino.



== Configurare i gruppi di protezione

.Prima di iniziare
Assicurarsi che i siti di origine e di destinazione siano configurati per:

* È installata la stessa versione di VMware Live Site Recovery
* Macchine virtuali
* Siti di ripristino e protezione associati
* Gli archivi dati di origine e di destinazione devono essere montati sui rispettivi siti


.Fasi
. Accedi a vCenter Server e seleziona *Site Recovery* > *Gruppi di protezione*.
. Nel riquadro *gruppi di protezione*, selezionare *nuovo*.
. Specificare un nome e una descrizione per il gruppo protezione, direzione e selezionare *Avanti*.
. Nel campo *Tipo*, seleziona l'opzione *Tipo...* come gruppi di datastore (replica basata su array) per datastore NFS e VMFS. Il dominio di errore è costituito esclusivamente da SVM con replica abilitata. Vengono visualizzate le SVM che hanno implementato solo il peering e non presentano problemi.
. Nella scheda gruppi di replica, selezionare la coppia di array abilitata o i gruppi di replica che hanno configurato la macchina virtuale, quindi selezionare *Avanti*.
+
Tutte le macchine virtuali presenti nel gruppo di replica vengono aggiunte al gruppo di protezione.

. È possibile selezionare il piano di ripristino esistente oppure crearne uno nuovo selezionando *Aggiungi al nuovo piano di ripristino.*
. Nella scheda Pronto per il completamento, esaminare i dettagli del gruppo di protezione creato, quindi selezionare *fine*.

