---
permalink: protect/configure-placeholder-datastores.html 
sidebar: sidebar 
keywords:  
summary: 'Configurare un datastore segnaposto per riservare spazio nell"inventario vCenter nel sito di ripristino per le macchine virtuali (VM) protette.  Gli archivi dati segnaposto richiedono una capacità minima, perché le VM segnaposto sono piccole e in genere utilizzano solo poche centinaia di kilobyte.' 
---
= Configurare i datastore segnaposto negli ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Configurare un datastore segnaposto per riservare spazio nell'inventario vCenter nel sito di ripristino per le macchine virtuali (VM) protette.  Gli archivi dati segnaposto richiedono una capacità minima, perché le VM segnaposto sono piccole e in genere utilizzano solo poche centinaia di kilobyte.

.Prima di iniziare
* Assicurarsi che i siti protetti e di ripristino siano connessi.
* Verificare che le mappature delle risorse siano state configurate.


.Fasi
. Accedere a vCenter Server e selezionare *Site Recovery* > *Sites*.
. Selezionare il sito protetto e selezionare *Gestisci*.
. Selezionare *segnaposto datastore* > *nuovo* nella scheda Gestisci per creare un nuovo archivio dati segnaposto.
. Selezionare l'archivio dati appropriato e selezionare *OK*.
+

NOTE: Gli archivi dati segnaposto possono risiedere su storage locali o remoti, ma non richiedono replica.

. Ripetere i passaggi da 3 a 5 per configurare un archivio dati segnaposto per il sito di ripristino.

