---
permalink: protect/enable-storage-replication-adapter.html 
sidebar: sidebar 
keywords:  
summary: I tool ONTAP per VMware vSphere offrono la possibilità di abilitare la funzionalità SRA per la configurazione del disaster recovery. 
---
= Configurare SRA negli ONTAP tools per proteggere i datastore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I tool ONTAP per VMware vSphere offrono la possibilità di abilitare la funzionalità SRA per la configurazione del disaster recovery.

.Prima di iniziare
* È necessario aver configurato l'istanza di vCenter Server e l'host ESXi configurato.
* Devi aver implementato tool ONTAP per VMware vSphere.
* Il `.tar.gz` file dell'adattatore SRA dovrebbe essere stato scaricato dal https://mysupport.netapp.com/site/products/all/details/otv10/downloads-tab["Sito di supporto NetApp"^] .
* Prima di eseguire i flussi di lavoro SRA, è necessario disporre delle stesse pianificazioni SnapMirror personalizzate sui cluster ONTAP di origine e di destinazione.
* link:../manage/enable-services.html["Abilita i tool ONTAP per i servizi VMware vSphere"] per abilitare la funzionalità SRA.


.Fasi
. Accedere all'interfaccia di gestione dell'appliance VMware Live Site Recovery utilizzando l'URL: `\https://:<srm_ip>:5480`, Quindi accedere a Storage Replication Adapter nell'interfaccia di gestione dell'appliance VMware Live Site Recovery.
. Selezionare *Nuova scheda*.
. Caricare il programma di installazione _.tar.gz_ per il plug-in SRA in VMware Live Site Recovery.
. Eseguire nuovamente la scansione delle schede di rete per verificare che i dettagli siano aggiornati nella pagina VMware Live Site Recovery Storage Replication Adapters (schede di replica storage di VMware Live Site Recovery).



NOTE: Dopo un failover, azioni quali espansione, montaggio ed eliminazione potrebbero non essere disponibili per i datastore.  Eseguire la scoperta del datastore per aggiornare e visualizzare le azioni appropriate del menu contestuale.


NOTE: Dopo ogni operazione di riprotezione, è necessario eseguire l'individuazione dello storage su entrambi i siti.

In una nuova configurazione con protezione SRA, eseguire sempre un failover di prova.  Saltare il failover di prova potrebbe causare il fallimento dell'operazione di riprotezione.

In una configurazione fan-out, dopo un failover SnapMirror Active Sync in cui la sorgente SnapMirror cambia nel sito B per Automated Failover Duplex e Asynchronous SnapMirror, eseguire un failover di prova tra i siti B e C. Saltare questo passaggio potrebbe comportare il fallimento dell'operazione di riprotezione.

.Informazioni correlate
https://docs.netapp.com/us-en/netapp-solutions-virtualization/vmware/vmw-nfs-vlsr.html#scenario-overview["Configurare il disaster recovery per i datastore NFS utilizzando VMware Site Recovery Manager"]
