---
permalink: protect/enable-storage-replication-adapter.html 
sidebar: sidebar 
keywords:  
summary: I tool ONTAP per VMware vSphere consentono di utilizzare la funzionalità SRA con i tool ONTAP per VMware vSphere per configurare il disaster recovery. 
---
= Abilitare SRA per proteggere i datastore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I tool ONTAP per VMware vSphere consentono di utilizzare la funzionalità SRA con i tool ONTAP per VMware vSphere per configurare il disaster recovery.

*Cosa ti serve*

* È necessario aver configurato l'istanza di vCenter Server e l'host ESXi configurato.
* Dovresti aver distribuito gli strumenti ONTAP.
* L'adattatore SRA dovrebbe essere stato scaricato `.tar.gz` dal https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Sito di supporto NetApp"^].


*Fasi*

. Accedere all'interfaccia di gestione delle appliance SRM utilizzando l'URL: `\https://:<srm_ip>:5480`, Quindi passare a Storage Replication Adapter nell'interfaccia di gestione degli appliance di VMware SRM.
. Selezionare *Nuova scheda*.
. Caricare il programma di installazione di _.tar.gz_ per il plug-in SRA su SRM.
. Eseguire nuovamente la scansione delle schede per verificare che i dettagli siano aggiornati sulle schede di replica dello storage SRM
pagina.

