---
permalink: concepts/ontap-tools-overview.html 
sidebar: sidebar 
keywords: ONTAP tools overview, virtual machine lifecycle, VASA Provider, disaster recovery 
summary: Scopri come ONTAP tools for VMware vSphere supporta la gestione del ciclo di vita dello storage delle macchine virtuali, il provisioning dei datastore e il disaster recovery. 
---
= Scopri gli strumenti ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools per VMware vSphere è una suite di strumenti per la gestione del ciclo di vita dello storage delle macchine virtuali. Si integra con l'ecosistema VMware per semplificare il provisioning dei datastore e fornire una protezione di base per le macchine virtuali. È una raccolta di microservizi scalabili orizzontalmente e basati su eventi, distribuiti come Open Virtual Appliance (OVA).

Gli ONTAP tools for VMware vSphere supportano:

* Funzionalità principali della macchina virtuale (VM) come protezione e ripristino di emergenza
* Fornitore VASA per la gestione basata su policy di archiviazione
* Gestione basata su criteri dello storage
* Storage Replication Adapter (SRA)


.Alta disponibilità per gli strumenti ONTAP per VMware
Gli ONTAP tools for VMware vSphere offrono supporto ad alta disponibilità (HA) per contribuire a mantenere un funzionamento ininterrotto in caso di guasti.

La soluzione HA ti aiuta a ripristinare rapidamente i seguenti tipi di interruzioni:

* Errore host: è supportato solo l'errore di un singolo nodo.
* Errore di rete
* Errore della macchina virtuale (sistema operativo guest)
* Errore dell'applicazione (strumenti ONTAP )


Non è necessario eseguire alcuna configurazione aggiuntiva per abilitare HA per gli ONTAP tools for VMware vSphere.

[NOTE]
====
Gli ONTAP tools for VMware vSphere non supportano vCenter HA.

====
Per utilizzare la funzionalità HA, assicurarsi che l'hot-add della CPU e l'hot-plug della memoria siano abilitati durante la distribuzione o nelle impostazioni della macchina virtuale.
