---
permalink: concepts/ontap-tools-concepts-terms.html 
sidebar: sidebar 
keywords:  
summary: Nella sezione seguente vengono descritti i concetti e i termini principali utilizzati nel documento. 
---
= Concetti e termini chiave
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nella sezione seguente vengono descritti i concetti e i termini principali utilizzati nel documento.



=== Autorità di certificazione (CA)

CA è un'entità attendibile che emette certificati SSL (Secure Sockets Layer).



=== Gruppo di coerenza

Un gruppo di coerenza è una raccolta di volumi gestiti come un'unica unità. I gruppi di coerenza vengono sincronizzati per garantire la coerenza dei dati tra unità di archiviazione e volumi. In ONTAP, forniscono una gestione semplice e una garanzia di protezione per un carico di lavoro applicativo che si estende su più volumi.  Scopri di più su https://docs.netapp.com/us-en/ontap/consistency-groups/index.html["gruppi di coerenza"] .



=== Stack doppio

Una rete dual-stack è un ambiente di rete che supporta l'utilizzo simultaneo di indirizzi IPv4 e IPv6.



=== Alta disponibilità (ha)

I nodi del cluster sono configurati in coppie ha per operazioni senza interruzioni.



=== LUN (Logical Unit Number)

Un LUN è un numero utilizzato per identificare un'unità logica all'interno di una SAN (Storage Area Network). Questi dispositivi indirizzabili sono in genere dischi logici a cui si accede tramite il protocollo SCSI (Small computer System Interface) o uno dei suoi derivati incapsulati.



=== Namespace e sottosistema NVMe

Uno spazio dei nomi NVMe è una quantità di memoria non volatile che può essere formattata in blocchi logici. Gli spazi dei nomi sono l'equivalente dei LUN per i protocolli FC e iSCSI e un sottosistema NVMe è analogo a un igroup. Un sottosistema NVMe può essere associato agli iniziatori, in modo che gli iniziatori associati possano accedere agli spazi dei nomi all'interno del sottosistema.



=== Gestione strumenti ONTAP

ONTAP Tools Manager offre un maggiore controllo sui tool ONTAP per gli amministratori di VMware vSphere sulle istanze di vCenter Server gestite e sui backend storage integrati. Aiuta a gestire istanze di vCenter Server, backend di storage, certificati, password e download dei bundle di log.



=== Open Virtual Appliance (OVA)

OVA è uno standard aperto per il packaging e la distribuzione di appliance virtuali o software che devono essere eseguiti su macchine virtuali.



=== Obiettivo RPO (Recovery Point Objective)

L'RPO misura la frequenza con cui si esegue il backup o la replica dei dati. Specifica il momento esatto in cui è necessario ripristinare i dati dopo un'interruzione per riprendere le operazioni aziendali. Ad esempio, se un'organizzazione ha un RPO di 4 ore, può tollerare la perdita di dati fino a 4 ore in caso di disastro.



=== Sincronizzazione attiva di SnapMirror

La sincronizzazione attiva di SnapMirror consente ai servizi di business di continuare a funzionare anche in caso di guasto completo del sito, supportando il failover delle applicazioni in modo trasparente utilizzando una copia secondaria. Non sono necessari interventi manuali o script personalizzati per attivare un failover con la sincronizzazione attiva di SnapMirror. Ulteriori informazioni su https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/index.html["Sincronizzazione attiva di SnapMirror"].



=== Back-end dello storage

I backend dello storage sono l'infrastruttura storage sottostante che l'host ESXi utilizza per memorizzare file, dati e altre risorse della macchina virtuale. Consentono all'host ESXi di accedere e gestire i dati persistenti, fornendo le performance e le funzionalità dello storage necessarie per un ambiente virtualizzato.

.Cluster globale (backend storage)
I backend di storage globale, disponibili solo con le credenziali del cluster ONTAP, sono inseriti nell'interfaccia di ONTAP tools Manager. Possono essere aggiunti con minimal Privileges per consentire il rilevamento delle risorse cluster essenziali necessarie per la gestione dei vVol. I cluster globali sono ideali per gli scenari multi-tenancy, in cui un utente SVM viene aggiunto localmente per la gestione dei vVol.

.Backend dello storage locale
I backend di storage locale con credenziali cluster o SVM vengono aggiunti tramite l'interfaccia utente dei tool ONTAP e sono limitati a un vCenter. Quando si utilizzano le credenziali del cluster a livello locale, le SVM associate vengono associate automaticamente mappate con vCenter per gestire vVol o VMFS. Per la gestione di VMFS, incluso SRA, i tool ONTAP supportano le credenziali SVM senza richiedere un cluster globale.



=== Storage Replication Adapter (SRA)

SRA è il software specifico del fornitore di soluzioni di storage installato all'interno dell'appliance VMware Live Site Recovery. L'adattatore consente la comunicazione tra Site Recovery Manager e uno storage controller a livello di Storage Virtual Machine (SVM) e la configurazione a livello del cluster.



=== Storage Virtual Machine (SVM)

SVM è l'unità di multi-tenancy in ONTAP. Come una macchina virtuale in esecuzione su un hypervisor, la SVM è un'entità logica che astrae le risorse fisiche. SVM contiene volumi di dati e una o più LIF attraverso i quali distribuiscono dati ai client.



=== Configurazione uniforme e non uniforme

* *Uniform host access* significa che gli host da due siti sono connessi a tutti i percorsi ai cluster di storage su entrambi i siti. I percorsi tra siti sono estesi su diverse distanze.
* *Accesso host non uniforme* significa che gli host in ogni sito sono connessi solo al cluster nello stesso sito. I percorsi tra siti e quelli estesi non sono connessi.
+

NOTE: È supportato un accesso host uniforme per qualsiasi implementazione SnapMirror Active Sync; l'accesso host non uniforme è supportato solo per le implementazioni Active/Active simmetriche. Ulteriori informazioni su https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/index.html["Panoramica della sincronizzazione attiva di SnapMirror in ONTAP"].





=== File system della macchina virtuale (VMFS)

VMFS è un file system in cluster progettato per la memorizzazione dei file delle macchine virtuali negli ambienti VMware vSphere.



=== Volumi virtuali (vVol)

I vVols forniscono un'astrazione a livello di volume per l'archiviazione utilizzata da una macchina virtuale.  Offre numerosi vantaggi e rappresenta un'alternativa all'utilizzo di una LUN tradizionale.  Un datastore vVol è in genere associato a un singolo LUN che funge da contenitore per i vVols.



=== Policy per lo storage delle VM

Le policy di storage delle macchine virtuali vengono create in vCenter Server in Policy e profili. Per vVol, creare un set di regole utilizzando le regole del provider di tipi di storage NetApp vVol.



=== Ripristino sito live di VMware

VMware Live Site Recovery, precedentemente noto come Site Recovery Manager (SRM), fornisce funzionalità di business continuity, disaster recovery, migrazione dei siti e test senza interruzioni per gli ambienti virtuali VMware.



=== API VMware vSphere per Storage Awareness (VASA)

VASA è un set di API che integrano gli storage array con vCenter Server per la gestione e l'amministrazione. L'architettura si basa su diversi componenti, tra cui il provider VASA, che gestisce la comunicazione tra VMware vSphere e i sistemi storage.



=== API storage di VMware vSphere: Integrazione degli array (VAAI)

VAAI è un set di API che consente la comunicazione tra gli host di VMware vSphere ESXi e i dispositivi storage. Le API comprendono un set di operazioni primitive utilizzate dagli host per scaricare operazioni di storage sull'array. VAAI può offrire miglioramenti significativi delle performance per i task a uso intensivo di storage.



=== VSphere Metro Storage Cluster

VSphere Metro Storage Cluster (vMSC) è un'architettura che consente e supporta vSphere in un'implementazione cluster estesa. Le soluzioni vMSC sono supportate con la sincronizzazione attiva di NetApp MetroCluster e SnapMirror (in precedenza SMBC). Queste soluzioni forniscono una migliore business continuity in caso di errore del dominio. Il modello di resilienza si basa sulle tue scelte specifiche di configurazione. Ulteriori informazioni su https://core.vmware.com/resource/vmware-vsphere-metro-storage-cluster-vmsc["Cluster di storage VMware vSphere Metro"].



=== Datastore vVol

Il datastore vVol è una rappresentazione del datastore logico di un contenitore vVol creato e gestito da un provider VASA.



=== RPO zero

RPO è l'acronimo di Recovery Point Objective, ovvero la quantità di perdita di dati ritenuta accettabile in un determinato periodo di tempo. Zero RPO indica che non è accettabile alcuna perdita di dati.
