---
permalink: automation/create-vvol-workflow.html 
sidebar: sidebar 
keywords: REST APIs, swagger 
summary: 'Un flusso di lavoro è una sequenza di uno o più passaggi necessari per eseguire un"attività o un obiettivo amministrativo specifico.' 
---
= Creare il datastore vVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi creare un datastore vVol con nuovi volumi o con volumi esistenti. Puoi anche creare un datastore vVol con la combinazione di volumi esistenti e nuovi volumi.


NOTE: Controllare che gli aggregati root non siano mappati alla SVM.

Generare un token JWT prima di creare datastore o aumentare la scadenza del token SAML impostando "durata massima token portante" su 60m su vCenter.

È necessario passare x-auth per l'API. È possibile generare questo x-auth dalla nuova API aggiunta in Auth in Swagger.

/virtualization/api/v1/auth/vcenter-login

. Crea un datastore vVol con un nuovo volume.


Ottieni l'id aggregato, storage_id (uuid SVM) utilizzando l'API REST di ONTAP.
POST /Virtualization/api/v1/vcenter/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvol/datastore

Utilizzare il seguente URI per controllare lo stato:

+

[listing]
----
`\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true`
----
+
Corpo della richiesta per datastore NFS

{
   "nome":"nfsds1",
   "protocollo":"nfs",
   "platform_type":"aff",
   "moref":"dominio-c8",
   "volumi":[
      {
         "is_existing":false,
         "name":"vol_nfs_pvt",
         "size_in_mb":2048000,
         "efficienza_spazio":"sottile",
         "aggregato":{
            "id":"d7078b3c-3827-4ac9-9273-0a3290945c2"
         },
         "qos":{
            "min_iops":200,
            "max_iops":5000
         }
      }
   ],
   "storage_backend":{
      "storage_id":"654c67bc-0f75-11ee-8a8c-00a09860a3ff"
   }
}

Corpo della richiesta per datastore iSCSI:
{
   "nome" : "iscsi_custom",
   "protocollo" : "iscsi",
   "platform_type": "AFF",
   "moref" : "dominio-c8",
   "volumi" : [
       {
           "is_existing" : falso,
           "nome" : "iscsi_custom",
           "dimensione_in_mb" : 8034,
           "efficienza_spazio" : "sottile",
           "aggregate" : {
               "id" : "54fe5d4-e461-49c8-bb2d-6d62c5d75af2"
           }
       }
   ],
   "nome_igroup_personalizzato": "igroup1",
   "storage_backend": {
                       "storage_id": "eb9d33ab-1960-11ee-9506-00a0985c6d9b" }
}
. Crea un datastore vVol con volumi esistenti.

Ottieni aggregate_id e volume_id utilizzando l'API REST di ONTAP.

 POST /virtualization/api/v1/vcenters/cdded9ad-6bsd-4c9e-b44g-691250bfe2df/vvols/datastores
Corpo della richiesta

....
 {
"name" : "nfsds2",
"protocol" : "nfs",
"platform_type": "aff",
"moref" : "domain-c8",
"volumes" : [
    {
          "is_existing": true,
          "id": "e632a632-1412-11ee-8a8c-00a09860a3ff"
        }
],
"storage_backend": {
                    "storage_id": "33a8b6b3-10cd-11ee-8a8c-00a09860a3ff"    }
....
}
