---
permalink: configure/add-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: I backend dello storage sono sistemi utilizzati dagli host ESXi per lo storage dei dati. 
---
= Aggiungere backend di archiviazione agli strumenti ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizza gli ONTAP tools for VMware vSphere per aggiungere e gestire i backend di storage per i tuoi host ESXi.  È possibile integrare cluster o SVM, abilitare il supporto MetroCluster e convalidare i certificati per una connettività sicura.  È possibile configurare i backend di archiviazione utilizzando ONTAP Tools Manager o il client vSphere, monitorare lo stato dei certificati e riscoprire manualmente le risorse dopo le modifiche al cluster.

Per aggiungere un backend di archiviazione in locale, utilizzare le credenziali del cluster o SVM nell'interfaccia degli strumenti ONTAP .  I backend di archiviazione locale sono disponibili solo per il vCenter Server selezionato. Gli strumenti ONTAP mappano le SVM sul vCenter Server per la gestione dei datastore vVols o VMFS.  Per i datastore VMFS e i flussi di lavoro SRA, è possibile utilizzare le credenziali SVM senza mappare un cluster a livello globale.

Per aggiungere un backend di archiviazione globale, utilizzare le credenziali del cluster ONTAP in ONTAP Tools Manager.  I backend di archiviazione globali consentono ai flussi di lavoro di individuazione di identificare le risorse del cluster necessarie per la gestione vVol.  Negli ambienti multitenant, è possibile aggiungere un utente SVM localmente per gestire i datastore vVols .

Se il supporto MetroCluster è abilitato in ONTAP, integrare sia i cluster di origine che quelli di destinazione come backend di archiviazione locali o globali.

.Prima di iniziare
Verificare che il certificato includa un campo Subject Alternative Name (SAN) valido.  I sistemi ONTAP utilizzano il campo SAN per identificare i LIF di gestione del cluster e dell'SVM.

[role="tabbed-block"]
====
.Utilizzo di ONTAP Tools Manager
--

NOTE: In un setup multi-tenant, puoi aggiungere un cluster backend storage a livello globale e una SVM locale per utilizzare le credenziali utente della SVM.

.Fasi
. Avviare Gestione strumenti ONTAP da un browser Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Effettua l'accesso con i tool ONTAP per le credenziali di amministratore di VMware vSphere fornite durante l'implementazione.
. Selezionare *backend di archiviazione* dalla barra laterale.
. Aggiungere il backend di archiviazione e fornire l'indirizzo IP del server o i dettagli FQDN, nome utente e password.
+

NOTE: Sono supportate le interfacce LIF di gestione indirizzi IPv4 e IPv6.

. Recupera automaticamente i certificati del cluster ONTAP e autorizza il certificato oppure caricalo manualmente navigando fino alla sua posizione.
+

NOTE: Se necessario, è possibile disabilitare la convalida del nome alternativo del soggetto (SAN) dalla console di manutenzione. Per le istruzioni, vederelink:../manage/change-valid-flag.html["Cambia il flag di convalida del certificato"] .

. Se il backend di archiviazione aggiunto fa parte di una configurazione MetroCluster , ONTAP Tools Manager mostra un messaggio pop-up per aggiungere il cluster peered.  Selezionare *Aggiungi* e fornire i dettagli per il backend di archiviazione peer MetroCluster .
+

NOTE: Dopo che il sistema ONTAP ha eseguito uno switchover e uno switchback, eseguire manualmente la scoperta degli strumenti ONTAP .



--
.Utilizzo dell'interfaccia utente del client vSphere
--

NOTE: I datastore vVols non supportano l'aggiunta diretta di un utente SVM tramite l'interfaccia utente del client vSphere.

. Accedere al client vSphere.
. Nella pagina Collegamenti, selezionare *NetApp ONTAP tools* nella sezione dei plug-in.
. Selezionare *backend di archiviazione* dalla barra laterale.
. Aggiungere il backend di archiviazione e fornire l'indirizzo IP del server, il nome utente, la password e i dettagli della porta.
+

NOTE: È possibile aggiungere un backend di archiviazione utilizzando credenziali basate su cluster con LIF di gestione IPv4 o IPv6.  Per aggiungere direttamente un utente SVM, fornire credenziali basate su SVM insieme a un LIF di gestione SVM.  Se un cluster è già stato integrato, non è possibile integrare nuovamente un utente SVM da quel cluster.

. Recupera automaticamente i certificati del cluster ONTAP e autorizza il certificato oppure caricalo manualmente navigando fino alla sua posizione.
. Se il backend di archiviazione aggiunto fa parte della configurazione MetroCluster , gli strumenti ONTAP visualizzano la schermata *Aggiungi peer MetroCluster *.  Selezionare *Aggiungi peer* per aggiungere il backend di archiviazione peer.
+

NOTE: Dopo che il sistema ONTAP ha eseguito uno switchover e uno switchback, eseguire manualmente la scoperta degli strumenti ONTAP .



.Cosa succederà?
Gli strumenti ONTAP aggiornano l'elenco per mostrare il nuovo backend di archiviazione.

--
====
Gli strumenti ONTAP elencano il backend di archiviazione appena aggiunto nella pagina *Backend di archiviazione*.  Se un certificato scade entro 30 giorni o meno, gli strumenti ONTAP mostrano un avviso nella colonna della data di scadenza del certificato.  Dopo la scadenza, gli strumenti ONTAP contrassegnano il backend di archiviazione come sconosciuto perché non riesce a connettersi al sistema di archiviazione.

.Informazioni correlate
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_configure_clusters.html["Configurazione dei cluster in una configurazione MetroCluster"]
