---
permalink: configure/configure-esx-server-multipath-and-timeout-settings.html 
sidebar: sidebar 
keywords:  
summary: 'I tool ONTAP per VMware vSphere controllano e impostano le impostazioni di multipathing dell"host ESXi e le impostazioni di timeout degli HBA più adatte ai sistemi storage NetApp.' 
---
= Configurare le impostazioni dell'host ESXi negli ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La configurazione delle impostazioni multipath e timeout del server ESXi aiuta a mantenere la disponibilità e l'integrità dei dati.  Abilita il failover automatico su un percorso di archiviazione di backup se il percorso primario non è più disponibile.



== Configurare le impostazioni di multipath e timeout del server ESXi

I tool ONTAP per VMware vSphere controllano e impostano le impostazioni di multipath host ESXi e le impostazioni di timeout HBA che funzionano meglio con i sistemi storage NetApp.

.A proposito di questa attività
Questo processo potrebbe richiedere del tempo, a seconda della configurazione e del carico del sistema.  È possibile visualizzare l'avanzamento nel pannello Attività recenti.

.Fasi
. Dalla home page del client Web VMware vSphere, selezionare *host e cluster*.
. Nella pagina dei collegamenti del client Web VMware vSphere, selezionare *NetApp ONTAP tools* nella sezione dei plug-in.
. Andare alla scheda *ESXi host compliance* nella panoramica (dashboard) degli strumenti ONTAP per il plug-in VMware vSphere.
. Selezionare il collegamento *Applica impostazioni consigliate*.
. Nella finestra *Applica impostazioni host consigliate*, seleziona gli host che desideri aggiornare per utilizzare le impostazioni consigliate NetApp e seleziona *Avanti*.
+

NOTE: È possibile espandere l'host ESXi per visualizzare i valori correnti.

. Nella pagina delle impostazioni, selezionare i valori consigliati secondo necessità.
. Nel pannello di riepilogo, controllare i valori e selezionare *fine*. È possibile tenere traccia dell'avanzamento nel riquadro attività recenti.




== Impostare i valori dell'host ESXi

Utilizzare gli ONTAP tools for VMware vSphere per impostare timeout e altri valori sugli host ESXi per prestazioni e failover ottimali.  Imposta questi valori in base ai test NetApp .

È possibile impostare i seguenti valori su un host ESXi:



=== Impostazioni adattatore HBA/CNA

Imposta i seguenti parametri sui valori predefiniti:

* Disk.QFullSampleSize
* Disk.QFullThreshold
* Timeout HBA FC Emulex
* Timeout HBA FC QLogic




=== Impostazioni MPIO

Le impostazioni MPIO selezionano i percorsi migliori per i sistemi di archiviazione NetApp .  Le impostazioni MPIO selezionano il percorso migliore e lo utilizzano.

Per ambienti ad alte prestazioni o quando si esegue il test con un singolo datastore LUN, regolare l'impostazione del bilanciamento del carico del criterio di selezione del percorso (PSP) round-robin (VMW_PSP_RR) per migliorare le prestazioni.  Imposta il valore IOPS predefinito da 1000 a 1.


NOTE: Le impostazioni MPIO non si applicano ai protocolli NVMe, NVMe/FC e NVMe/TCP.



=== Impostazioni NFS

|===


| Parametro | Impostare questo valore su... 


| NET.TcpipelHeapSize | 32 


| NET.TcpipelHeapMax | 1024 MB 


| NFS.MaxVolumes | 256 


| NFS41.MaxVolumes | 256 


| NFS.MaxQueueDepth | 128 o superiore 


| NFS.HeartbeatMaxFailures | 10 


| NFS.HeartbeatFrequency | 12 


| NFS.HeartbeatTimeout | 5 
|===