---
permalink: configure/configure-network-access.html 
sidebar: sidebar 
keywords: configure network access, ONTAP export policy, ESXi host IP allowlist, ONTAP tools mount access 
summary: 'Configura l"accesso di rete per controllare quali indirizzi IP degli host ESXi vengono aggiunti alle policy di esportazione in ONTAP tools.' 
---
= Configurare l'accesso alla rete negli ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per impostazione predefinita, tutti gli indirizzi IP rilevati dall'host ESXi vengono aggiunti automaticamente al criterio di esportazione, a meno che non si configuri l'accesso alla rete.  È possibile modificare i criteri di esportazione per consentire l'accesso solo da indirizzi IP specifici.  Se un host ESXi escluso tenta un'operazione di montaggio, l'operazione fallisce.

.Fasi
. Accedere al client vSphere.
. Selezionare *NetApp ONTAP tools* nella pagina dei collegamenti nella sezione dei plug-in.
. Nel riquadro sinistro degli strumenti ONTAP , vai su *Impostazioni* > *Gestisci accesso alla rete* > *Modifica*.
+
Per aggiungere più indirizzi IP, separare l'elenco con virgole, intervalli, Classless Inter-Domain Routing (CIDR) o una combinazione dei tre.

. Selezionare *Salva*.

