---
permalink: configure/discover-storage-systems-and-hosts.html 
sidebar: sidebar 
keywords:  
summary: Quando si eseguono per la prima volta i tool ONTAP per VMware vSphere in un client vSphere, i tool ONTAP per VMware vSphere scoprono gli host ESXi, le relative LUN e le esportazioni NFS e i sistemi storage NetApp che gestiscono tali LUN ed esportazioni. 
---
= Rilevamento di host e sistemi storage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando gli ONTAP tools for VMware vSphere vengono avviati per la prima volta in vSphere Client, rilevano automaticamente gli host ESXi, i LUN associati e le esportazioni NFS, nonché i sistemi di storage NetApp che possiedono tali risorse.

.Prima di iniziare
* Assicurarsi che tutti gli host ESXi siano accesi e connessi.
* Assicurarsi che tutte le macchine virtuali di archiviazione (SVM) da rilevare siano in esecuzione e che ogni nodo del cluster disponga di almeno un LIF dati configurato per il protocollo di archiviazione in uso (NFS o iSCSI).


.A proposito di questa attività
È possibile scoprire nuovi sistemi di archiviazione o aggiornare quelli esistenti per ottenere i dettagli più recenti su capacità e configurazione.  È anche possibile modificare gli ONTAP tools for VMware vSphere per l'accesso al sistema di storage.

Durante il rilevamento dei sistemi storage, i tool di ONTAP per VMware vSphere raccolgono informazioni dagli host ESXi gestiti dall'istanza di vCenter Server.

.Fasi
. Dalla home page di vSphere Client, selezionare *host e cluster*.
. Fare clic con il pulsante destro del mouse sul data center desiderato e selezionare *Strumenti NetApp ONTAP * > *Aggiorna dati host*.
+
Nella finestra di dialogo *Conferma*, confermare la scelta.

. Selezionare i controller di archiviazione rilevati che hanno lo stato `Authentication Failure` e selezionare *azioni* > *Modifica*.
. Inserire le informazioni richieste nella finestra di dialogo *Modify Storage System* (Modifica sistema di storage).
. Ripetere i passaggi 4 e 5 per tutti i controller storage con `Authentication Failure` stato.


Al termine del processo di rilevamento, eseguire le seguenti operazioni:

* Utilizzare gli strumenti ONTAP per VMware vSphere per configurare le impostazioni dell'host ESXi per gli host che visualizzano l'icona di avviso nella colonna delle impostazioni dell'adattatore, nella colonna delle impostazioni MPIO o nella colonna delle impostazioni NFS.
* Fornire le credenziali del sistema storage.

