---
permalink: configure/esxi-host-values.html 
sidebar: sidebar 
keywords:  
summary: È possibile impostare timeout e altri valori sugli host ESXi utilizzando gli strumenti ONTAP per VMware vSphere per garantire le migliori performance e il failover corretto. I valori dei tool ONTAP per i set VMware vSphere si basano su test NetApp interni. 
---
= Impostare i valori dell'host ESXi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizzando gli strumenti ONTAP per VMware vSphere, è possibile impostare timeout e altri valori sugli host ESXi per garantire le migliori prestazioni e il successo del failover. I valori dei tool ONTAP per i set VMware vSphere si basano su test NetApp interni.

È possibile impostare i seguenti valori su un host ESXi:



== Impostazioni adattatore HBA/CNA

Consente di impostare le impostazioni di timeout dell'HBA consigliate per i sistemi di archiviazione NetApp.

|===
| Parametri | Impostare questo valore su... 


| Disk.QFullSampleSize | 32 per tutte le configurazioni. L'impostazione di questo valore aiuta a prevenire gli errori di i/O. 


| Disk.QFullThreshold | 8 per tutte le configurazioni. L'impostazione di questo valore aiuta a prevenire gli errori di i/O. 


| Timeout HBA FC Emulex | Valore predefinito. 


| Timeout HBA FC QLogic | Valore predefinito. 
|===


== Impostazioni MPIO

Le impostazioni MPIO definiscono i percorsi preferiti per i sistemi storage NetApp. Determinano quali percorsi disponibili sono ottimizzati (rispetto a quelli non ottimizzati che attraversano il cavo di interconnessione) e impostano il percorso preferito su uno di tali percorsi.

Negli ambienti a performance elevate o quando si eseguono test delle performance con un singolo datastore LUN, prendere in considerazione la possibilità di modificare l'impostazione del bilanciamento del carico della policy di selezione del percorso psp (round-robin) VMW_PSP_RR (Path Selection Policy) dall'impostazione IOPS predefinita di 1000 a un valore di 1.



== Impostazioni NFS

|===


| Parametro | Impostare questo valore su... 


| NET.TcpipelHeapSize | 32 


| NET.TcpipelHeapMax | 1024 MB 


| NFS.MaxVolumes | 256 


| NFS41.MaxVolumes | 256 


| NFS.MaxQueueDepth | 128 o superiore 


| NFS.HeartbeatMaxFailures | 10 


| NFS.HeartbeatFrequency | 12 


| NFS.HeartbeatTimeout | 5 
|===