---
permalink: configure/install-nfs-vaai-plug-in.html 
sidebar: sidebar 
keywords:  
summary: 'Puoi installare il plug-in NFS NetApp per le API vStorage di VMware per l"integrazione degli array \(VAAI\) utilizzando i tool ONTAP per VMware vSphere.' 
---
= Installare il plug-in NFS VAAI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi installare il plug-in NFS NetApp per le API vStorage di VMware per l'integrazione degli array (VAAI) utilizzando i tool ONTAP per VMware vSphere.

*Cosa ti serve*

* Dovresti aver scaricato il pacchetto di installazione per il plug-in NFS per VAAI (`.vib`) Dal NetApp Support Site. https://mysupport.netapp.com/site/products/all/details/nfsplugin-vmware-vaai/downloads-tab["Plug-in NetApp NFS per VMware VAAI"]
* Si dovrebbe avere installato ESXi host 7.0U3 ultima patch come versione minima e ONTAP 9.12.1Px (ultima versione P) 9.13.1Px, 9.14.1Px, o successiva.
* L'host ESXi dovrebbe essere stato alimentato e montato un datastore NFS.
* È necessario impostare i valori di `DataMover.HardwareAcceleratedMove`, `DataMover.HardwareAcceleratedInit`, e. `VMFS3.HardwareAcceleratedLocking` impostazioni host su "`1`".
+
Questi valori vengono impostati automaticamente sull'host ESXi quando viene aggiornata la finestra di dialogo Recommended Settings (Impostazioni consigliate).

* L'opzione vstorage dovrebbe essere stata attivata sulla macchina virtuale di storage (SVM) utilizzando `vserver nfs modify -vserver vserver_name -vstorage enabled` comando.
* Se si utilizza il plug-in NetApp NFS VAAI 2,0, si dovrebbe avere ESXi 7.0U3 o versione successiva.
* È necessario disporre delle ultime release di patch di vSphere 7.0U3 poiché vSphere 6,5 è stato obsoleto.
* VSphere 8.x è supportato con il plug-in NetApp NFS VAAI 2,0.1 (build 16).


*Fasi*

. Fare clic su *Impostazioni* nella home page degli strumenti di ONTAP per VMware vSphere.
. Fare clic sulla scheda *NFS VAAI Tools* (Strumenti VAAI NFS).
. Quando il plug-in VAAI viene caricato su vCenter Server, seleziona *Cambia* nella sezione *versione esistente*. Se un plug-in VAAI non viene caricato in vCenter Server, selezionare il pulsante *carica*.
. Individuare e selezionare `.vib` Quindi fare clic su *carica* per caricare il file sugli strumenti ONTAP.
. Fare clic su *Install on EXSI host*, selezionare l'host ESXi su cui si desidera installare il plug-in NFS VAAI, quindi fare clic su *Install*.
+
Vengono visualizzati solo gli host ESXi idonei per l'installazione del plug-in. Per completare l'installazione, seguire le istruzioni visualizzate sullo schermo. È possibile monitorare l'avanzamento dell'installazione nella sezione Recent Tasks (attività recenti) di vSphere Web Client.

. Al termine dell'installazione, riavviare manualmente l'host ESXi.
+
Quando l'amministratore VMware riavvia l'host ESXi, i tool ONTAP per VMware vSphere rilevano automaticamente il plug-in NFS VAAI. Non è necessario eseguire ulteriori operazioni per attivare il plug-in.


