---
permalink: configure/install-nfs-vaai-plug-in.html 
sidebar: sidebar 
keywords:  
summary: 'Puoi installare il plug-in NFS NetApp per le API vStorage di VMware per l"integrazione degli array \(VAAI\) utilizzando i tool ONTAP per VMware vSphere.' 
---
= Installare il plug-in NFS VAAI utilizzando gli strumenti ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il plug-in NFS vStorage API for Array Integration (NFS VAAI) collega VMware vSphere agli array di archiviazione NFS.  Utilizzare gli ONTAP tools for VMware vSphere per installare il plug-in VAAI. Ciò consente all'array di storage NFS di gestire determinate operazioni di storage al posto degli host ESXi.

.Prima di iniziare
* Scaricare il https://mysupport.netapp.com/site/products/all/details/nfsplugin-vmware-vaai/downloads-tab["Plug-in NetApp NFS per VMware VAAI"] pacchetto di installazione.
* Assicurarsi di disporre dell'host ESXi e della patch più recente di vSphere 7.0U3 o versioni successive e di ONTAP 9.14.1 o versioni successive.
* Montare un datastore NFS.


.Fasi
. Accedere al client vSphere.
. Selezionare *tasti di scelta rapida* > *NetApp ONTAP tools* nella sezione dei plug-in.
. Selezionare *Impostazioni* > *NFS VAAI Tools*.
. Se hai già caricato il plug-in VAAI su vCenter Server, seleziona *Modifica* in *Versione esistente*.  In caso contrario, seleziona *Carica*.
. Sfogliare e selezionare il `.vib` file e selezionare *carica* per caricare il file negli strumenti ONTAP.
. Selezionare *Installa su host ESXI*, selezionare l'host ESXi su cui si desidera installare il plug-in NFS VAAI, quindi selezionare *Installa*.
+
vSphere Web Client mostra solo gli host ESXi che possono installare il plug-in. È possibile monitorare l'avanzamento dell'installazione nella sezione Attività recenti.

. Riavviare l'host ESXi manualmente dopo l'installazione.
+
Dopo aver riavviato l'host ESXi, gli ONTAP tools for VMware vSphere rilevano e abilitano automaticamente il plug-in NFS VAAI.



.Quali sono le prossime novità?
Dopo aver installato il plug-in NFS VAAI e riavviato l'host ESXi, configurare i criteri di esportazione NFS per l'offload della copia VAAI.  Assicurarsi che le norme sulla politica di esportazione soddisfino questi requisiti:

* Il volume ONTAP pertinente consente chiamate NFSv4.
* L'utente root rimane root e NFSv4 è consentito in tutti i volumi padre di giunzione.
* L'opzione per il supporto VAAI è impostata sul server NFS pertinente.


Per maggiori informazioni, fare riferimento a https://kb.netapp.com/on-prem/ontap/DM/VAAI/VAAI-KBs/Configure_the_correct_NFS_export_policies_for_VAAI_copy_offload["Configura le policy di esportazione NFS corrette per l'offload delle copie VAAI"] Articolo della Knowledge Base.

.Informazioni correlate
https://docs.netapp.com/us-en/ontap/nfs-admin/support-vmware-vstorage-over-nfs-concept.html["Supporto per VMware vStorage su NFS"]

https://docs.netapp.com/us-en/ontap/nfs-admin/enable-disable-nfsv40-task.html["Attivare o disattivare NFSv4.0"]

https://docs.netapp.com/us-en/ontap/nfs-admin/ontap-support-nfsv42-concept.html#nfs-v4-2-security-labels["Supporto ONTAP per NFSv4.2"]
