---
permalink: configure/protect-cluster.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: I tool ONTAP per VMware vSphere gestiscono la protezione dei cluster di host. 
---
= Proteggere utilizzando la protezione del cluster host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I tool ONTAP per VMware vSphere gestiscono la protezione dei cluster di host. Tutti i datastore appartenenti alla SVM selezionata e montati su uno o più host del cluster sono protetti in un cluster di host.

.Prima di iniziare
Prima di proteggere un cluster host, assicurati di soddisfare questi requisiti:

* Il cluster host contiene solo datastore provenienti da una singola SVM.
* Gli archivi dati sul cluster host non vengono montati su host esterni al cluster.
* I datastore montati sul cluster host sono datastore VMFS con protocollo iSCSI o FC.  Non è possibile utilizzare datastore vVols, NFS o VMFS con i protocolli NVMe/FC e NVMe/TCP.
* I datastore basati su volumi FlexVol/LUN montati su un host non fanno parte di alcun gruppo di coerenza.
* I datastore basati su volumi FlexVol/LUN montati su un host non fanno parte di alcuna relazione SnapMirror .
* Il cluster host contiene almeno un datastore.


.Fasi
. Accedere al client vSphere.
. Fare clic con il pulsante destro del mouse su un cluster host e selezionare *Strumenti NetApp ONTAP * > *Proteggi cluster*.
. Nella finestra di protezione del cluster, il sistema compila automaticamente i dettagli relativi al tipo di datastore e alla macchina virtuale (VM) di archiviazione di origine.  Selezionare il collegamento datastore per visualizzare i datastore protetti.
. Selezionare *Aggiungi relazione*.
. Nella finestra *Aggiungi relazione SnapMirror*, selezionare la VM di archiviazione di destinazione* e il tipo *criterio*.
+
Il tipo di criterio può essere asincrono o AutomatedFailOverDuplex.

+
Quando Aggiungi la relazione SnapMirror come policy di tipo AutomatedFailOverDuplex, devi aggiungere la VM storage di destinazione come backend dello storage al medesimo vCenter in cui vengono implementati i tool ONTAP per VMware vSphere.

+
Nel tipo di policy AutomatedFailOverDuplex sono presenti configurazioni host uniformi e non uniformi.  Quando si seleziona il pulsante di attivazione/disattivazione *configurazione host uniforme*, la configurazione del gruppo di iniziatori host viene replicata implicitamente sul sito di destinazione. Per ulteriori informazioni, fare riferimento a link:../concepts/ontap-tools-concepts-terms.html["Concetti e termini chiave"] .

. Se si sceglie di avere una configurazione host non uniforme, selezionare l'accesso host (origine/destinazione) per ogni host all'interno di quel cluster.
. Selezionare *Aggiungi*.
. È possibile modificare la protezione del cluster host utilizzando l'operazione *Modifica protezione del cluster host*.  È possibile modificare o eliminare le relazioni utilizzando le opzioni del menu con i puntini di sospensione.
. Selezionare il pulsante *Proteggi*.
+
Il sistema crea un'attività vCenter con i dettagli dell'ID processo e ne mostra l'avanzamento nel pannello delle attività recenti.  Si tratta di un'attività asincrona: l'interfaccia utente mostra solo lo stato di invio della richiesta e non attende il completamento dell'attività.

. Per visualizzare i cluster host protetti, andare su *Strumenti NetApp ONTAP * > *Protezione* > *Relazioni tra cluster host*.  Selezionare un gruppo di coerenza per visualizzarne la capacità, i datastore associati e i gruppi di coerenza figlio.


[NOTE]
====
Se è necessario rimuovere la protezione entro un'ora dalla creazione, eseguire prima l'individuazione dello storage.

====
.Informazioni correlate
https://www.vmware.com/docs/vmware-vsphere-metro-storage-cluster-vmsc["Cluster di archiviazione metro VMware vSphere (vMSC)"^]
