---
permalink: configure/registration-process.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile registrare il provider VASA con un"istanza di vCenter Server utilizzando gli ONTAP tools for VMware vSphere .' 
---
= Registrare il provider VASA con un'istanza del server vCenter negli ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizzare gli ONTAP tools for VMware vSphere per registrare il provider VASA con un'istanza di vCenter Server.  Ciò consente la gestione basata su policy di storage, il supporto vVols e l'integrazione con appliance VMware Live Site Recovery su sistemi ONTAP .

Le impostazioni del provider VASA mostrano lo stato di registrazione per il vCenter Server selezionato.

.Fasi
. Accedere al client vSphere.
. Selezionare *tasti di scelta rapida* > *NetApp ONTAP tools* nella sezione dei plug-in.
. Selezionare *Impostazioni* > *Impostazioni provider VASA*.  Gli strumenti ONTAP visualizzano lo stato di registrazione del fornitore VASA come non registrato.
. Selezionare il pulsante *Registra* per registrare il provider VASA.
. Inserisci un nome e le credenziali per il fornitore VASA.  Il nome utente può contenere solo lettere, numeri e caratteri di sottolineatura.  Impostare la lunghezza della password tra 8 e 256 caratteri.
. Selezionare *Registra*.
. Dopo una registrazione riuscita e l'aggiornamento della pagina, gli strumenti ONTAP visualizzano lo stato, il nome e la versione del provider VASA registrato.


.Cosa succederà
Verificare che il provider VASA integrato sia elencato sotto VASA Provider dal client vCenter:

.Fasi
. Accedere all'istanza di vCenter Server.
. Accedere con le credenziali di amministratore.
. Selezionare *Storage Providers* > *Configure*. Verificare che il provider VASA incorporato sia elencato correttamente.

