---
permalink: release-notes/whats-new.html 
sidebar: sidebar 
keywords: ONTAP tools 10.6, VMware vSphere release notes, datastore protection, audit logging, nconnect 
summary: Scopri le nuove funzionalità e i miglioramenti in ONTAP tools for VMware vSphere 10.6. 
---
= Novità degli ONTAP tools per VMware vSphere 10.6
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri le nuove funzionalità e i miglioramenti in ONTAP tools for VMware vSphere 10.6.



[[granular-datastore-protection]]
== Protezione granulare del datastore

ONTAP tools 10.6 introduce la protezione a livello di datastore, così puoi applicare la protezione a datastore selezionati invece che a un intero cluster host.

I principali miglioramenti includono:

* Protezione a livello di datastore per sistemi ONTAP e sistemi ASA r2
* Failover Duplex automatizzato (AFD) e politiche di protezione asincrone
* Supporto per i datastore iSCSI e FC VMFS
* Gruppi di coerenza gerarchica e configurazioni fan-out
* Controllo sull'appartenenza al gruppo di coerenza selezionando quali archivi dati proteggere insieme
* Configurazioni di protezione AFD uniformi e non uniformi
* Possibilità di modificare la protezione aggiungendo o rimuovendo datastore e host
* Flusso di lavoro di protezione del datastore nel plug-in vCenter
* Percorso di aggiornamento dalla protezione a livello di cluster host alla protezione a livello di datastore




[[audit-logging]]
== Registrazione degli eventi di controllo

ONTAP tools 10.6 aggiunge la registrazione degli eventi di controllo per migliorare la sicurezza e la tracciabilità operativa.

La registrazione degli eventi di controllo include:

* Tutte le chiamate API REST non GET, inclusi i dettagli della richiesta e della risposta
* Job di rilevamento, job di bundle AutoSupport, job di pulizia e operazioni della console di manutenzione
* Protezione dell'integrità degli archivi dei registri di controllo, inclusi avvisi di manomissione e cancellazione
* Supporto per l'inoltro Syslog


Questi aggiornamenti supportano i requisiti di conformità e sicurezza.



[[nconnect-support-for-nfs-datastores]]
== Supporto nconnect per datastore NFS

ONTAP tools 10.6 aggiunge il supporto nconnect per i datastore NFS di VMware, consentendo più connessioni TCP parallele tra host ESXi e datastore NFS ONTAP.

Questa versione supporta:

* nconnect per i datastore NFSv3 durante il provisioning
* nconnect per i datastore NFSv4.1 durante il provisioning con vCenter 8.0U3 e versioni successive
* Modifica del valore massimo di nconnect sugli host ESXi


Questo aiuta a migliorare il throughput e le prestazioni del datastore NFS per i carichi di lavoro multi-VM.



[[smaller-default-deployment-with-xs-profile]]
== Distribuzione predefinita più piccola con profilo XS

ONTAP tools 10.6 introduce un profilo di distribuzione predefinito extra-small (XS) più piccolo per ridurre il sovraccarico di risorse e semplificare la distribuzione iniziale.

I miglioramenti includono:

* XS come configurazione predefinita per la distribuzione iniziale
* Distribuzione OVA con impostazioni hardware predefinite ottimizzate
* Supporto per il provisioning del datastore, la protezione, l'abilitazione del servizio SRA e la modalità HA con XS
* Quattro profili di distribuzione disponibili nell'interfaccia utente di Manager: extra-small (XS), small (S), medium (M) e large (L)


Questo modello offre un ingombro iniziale ridotto con un chiaro percorso di scalabilità.



[[ease-of-deployment-improvement]]
== Miglioramento della facilità di implementazione

ONTAP tools 10.6 abilita per impostazione predefinita l'aggiunta a caldo della CPU e la connessione a caldo della memoria per le nuove installazioni della VM principale di ONTAP tools.

Questo elimina la necessità di abilitare manualmente queste impostazioni prima o dopo la distribuzione.



[[protection-workflow-improvement]]
== Miglioramento del flusso di lavoro di protezione

ONTAP tools 10.6 elimina la necessità di avviare manualmente il rilevamento dello storage quando i cluster ONTAP non sono disponibili, semplificando i flussi di lavoro di protezione.



[[platform-and-interoperability-qualification]]
== Qualificazione della piattaforma e dell'interoperabilità

ONTAP tools 10.6 amplia il supporto per la piattaforma e l'interoperabilità tra le principali release di ONTAP e VMware, consentendo una perfetta integrazione dello storage NetApp negli ambienti VMware.

Questa versione è allineata alle configurazioni correnti della piattaforma ONTAP e alle versioni di VMware, riducendo la complessità operativa durante gli aggiornamenti della piattaforma e gli aggiornamenti dello stack VMware.



[[supportability-enhancements]]
== Miglioramenti alla supportabilità

ONTAP tools 10.6 migliora la risoluzione dei problemi e la gestione del ciclo di vita.

Gli aggiornamenti principali includono:

* Eliminazione forzata per voci vCenter irraggiungibili o obsolete
* Migrazione da  `ntpd` a  `chronyd` per la sincronizzazione dell'ora, con migrazione automatica delle impostazioni del server NTP esistente durante l'upgrade
* Opzione della console di manutenzione per rinnovare i certificati dei servizi interni, anche dopo la scadenza
* Supporto sia per i server NTP tradizionali che per i server chrony basati su RHEL tramite il protocollo NTP standard (porta UDP 123)


Per i dettagli più recenti sulla compatibilità delle versioni, consulta  https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp"^].
