---
permalink: release-notes/whats-new.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 10.5, ONTAP tools for VMware vSphere' 
summary: Scopri le nuove funzionalità disponibili negli ONTAP tools for VMware vSphere 10.5. 
---
= Novità negli ONTAP tools for VMware vSphere 10.5
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scopri le nuove funzionalità disponibili negli ONTAP tools for VMware vSphere 10.5.

* *Qualifica della piattaforma*


Gli ONTAP tools for VMware vSphere 10.5 aggiungono il supporto per i sistemi ASA r2, garantendo la compatibilità con le configurazioni hardware e software più recenti.  Questa versione include anche l'integrazione con ONTAP 9.16.1 e 9.17.1, ampliando gli ambienti supportati.

* *Qualificazioni e certificazioni VMware*


Gli ONTAP tools for VMware vSphere 10.5 sono conformi agli attuali standard di certificazione di interoperabilità VMware, supportando sia l'host ESXi che vCenter Server.

* * Supporto MetroCluster *


Questa versione introduce il supporto per le configurazioni MetroCluster (MCC), migliorando le capacità di elevata disponibilità e di ripristino di emergenza.

* *Gestione della sicurezza e dei certificati*


Questa versione introduce una gestione semplificata dei certificati autofirmati, migliorando sia l'esperienza utente sia l'aderenza agli standard di sicurezza.  Fornisce flussi di lavoro di convalida dei certificati migliorati per proteggere ONTAP e gli ONTAP tools for VMware vSphere .

* *Miglioramenti della replicazione*


Questa versione supporta la replica VMFS con gruppo di coerenza gerarchica, inclusi SRA e SnapMirror ActiveSync nei sistemi ASA r2.  Supporta backup RPO pari a zero per migliorare la protezione e il ripristino dei dati.

* *Aggiornamento e migrazione*


Il processo di aggiornamento e migrazione dalle versioni precedenti degli ONTAP tools for VMware vSphere agli ONTAP tools for VMware vSphere 10.5 è progettato per essere fluido ed efficiente, riducendo al minimo i tempi di inattività e garantendo una transizione fluida.



== Piattaforme ONTAP supportate e versioni di vCenter Server

Per i dettagli più recenti sulla compatibilità delle versioni, fare riferimento a https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^] .
