---
permalink: manage/add-vsphere-host.html 
sidebar: sidebar 
keywords: add vSphere host, ONTAP tools host discovery, register ESXi host, VMware host management 
summary: Aggiungi host VMware vSphere agli ONTAP tools for VMware vSphere. 
---
= Aggiungere host VMware vSphere a ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aggiungere nuovi host VMware vSphere agli ONTAP tools for VMware vSphere per gestire e proteggere i datastore sugli host.

.Fasi
. Aggiungi un host al tuo cluster vSphere seguendo le  https://techdocs.broadcom.com/["Documentazione Tecnica Broadcom"].
. Dopo aver aggiunto l'host, vai al menu principale degli strumenti ONTAP e seleziona *Scopri* nel pannello di panoramica. Attendi il completamento del processo di scoperta. In alternativa, è possibile attendere il completamento della rilevazione dell'host pianificata.


.Risultato
Il nuovo host è ora rilevato e gestito dagli ONTAP tools for VMware vSphere. È possibile procedere alla gestione del datastore sul nuovo host.

.Argomenti correlati
* link:../manage/mount-a-vvols-datastore.html["Montare un datastore vVols"]sui nuovi host.
* link:../manage/mount-datastores-on-host.html["Montare il datastore NFS e VMFS"]sui nuovi host.

