---
permalink: manage/configure-remote-diagnostic-access.html 
sidebar: sidebar 
keywords: remote diagnostic access, ONTAP tools SSH diag user, enable SSH diagnostics, appliance troubleshooting access 
summary: 'Abilita l"accesso SSH per l"utente diag in ONTAP tools for VMware vSphere.' 
---
= Configurare l'accesso diagnostico remoto per ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile configurare i tool ONTAP per VMware vSphere per abilitare l'accesso SSH per l'utente diag.

.Prima di iniziare
Abilita l'estensione VASA Provider per la tua istanza di vCenter Server.

.A proposito di questa attività
L'utilizzo di SSH per accedere all'account utente DIAG presenta le seguenti limitazioni:

* è consentito un solo account di accesso per ogni attivazione di SSH.
* L'accesso SSH all'account utente DIAG viene disattivato quando si verifica una delle seguenti condizioni:
+
** Il tempo scade.
+
La sessione di accesso scade a mezzanotte del giorno successivo.

** Si accede nuovamente come utente di DIAG utilizzando SSH.




.Fasi
. Accedi al vCenter Server.
. Individua la macchina virtuale ONTAP tools e avvia la console web.
. Accedi utilizzando le `maint` credenziali.
. Immettere `4` per selezionare *supporto e diagnostica*.
. Entra `2` per selezionare *Abilita accesso alla diagnostica remota*.
. Invio `y` Nella finestra di dialogo Confirmation (Conferma) per abilitare l'accesso remoto alla diagnostica.
. Inserire una password per l'accesso remoto alla diagnostica.

