---
permalink: manage/delete-ds.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: 'L"azione Elimina archivio dati elimina il datastore. Nel caso del datastore NFS o VMFS, viene visualizzata una finestra di dialogo con l"elenco delle macchine virtuali che utilizzano il datastore.' 
---
= Elimina datastore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questa pagina descrive come eliminare i datastore NFS, VMFS o vVols utilizzando gli strumenti ONTAP in vCenter Server.

Quando si elimina un datastore, vengono eseguite le seguenti azioni a seconda del tipo di datastore:

* Il contenitore vVol è smontato.
* Se l'igroup non è in uso, iqn viene rimosso dall'igroup.
* Il contenitore vVol è stato eliminato.
* I volumi flessibili vengono lasciati nell'array di archiviazione.


È possibile eliminare il datastore solo se non sono presenti vVols sul datastore selezionato.

.Fasi
. Accedere al client vSphere.
. Fare clic con il pulsante destro del mouse su un sistema host, un cluster host o un data center e selezionare *Strumenti NetApp ONTAP * > *Elimina datastore*.
+

NOTE: Non è possibile eliminare un datastore utilizzato dalle macchine virtuali.  Spostare le macchine virtuali in un altro datastore prima di eliminarle.  Non è possibile eliminare il volume se fa parte di un cluster host protetto.

+
.. Nel caso di un datastore NFS o VMFS, viene visualizzata una finestra di dialogo con l'elenco delle VM che utilizzano il datastore.
.. Se nessuna macchina virtuale è associata a un datastore VMFS, verrà visualizzata una finestra di dialogo di conferma.  Se la protezione del cluster host è abilitata ed esiste una relazione AFD, è possibile pulire gli elementi di archiviazione secondaria.
.. Per i datastore VMFS protetti sui sistemi ASA r2, rimuovere la protezione prima di eliminare. A partire da ONTAP 9.17.1 e ONTAP tools for VMware vSphere 10.5, è possibile eliminare un datastore protetto.  Se è l'unico datastore nel gruppo di protezione, la protezione del cluster host viene rimossa automaticamente.
.. Per i datastore vVols , è possibile eliminare il datastore solo se non sono presenti vVols .  La finestra di dialogo *Elimina datastore* include un'opzione per rimuovere volumi dal cluster ONTAP .
.. Per i datastore vVols sui sistemi ASA r2, non è possibile eliminare i volumi di supporto da ONTAP utilizzando l'opzione *Elimina datastore*.


. Per eliminare i volumi di backup sull'archiviazione ONTAP, selezionare *Elimina volumi sul cluster ONTAP*.
+

NOTE: Per i datastore VMFS su storage ONTAP unificato che fanno parte di un cluster host protetto, non è possibile eliminare il volume dal cluster ONTAP .



Quando si elimina un datastore NFS, VMFS o vVols , gli igroup padre rimangono sul sistema ONTAP . Gli igroup figlio che non sono mappati ad alcun LUN vengono eliminati automaticamente. Gli strumenti ONTAP eseguono una pulizia giornaliera per rimuovere gli igroup padre predefiniti non mappati. Eliminare manualmente gli igroup padre personalizzati in ONTAP.  Gli strumenti ONTAP non possono riutilizzare igroup padre obsoleti.
