---
permalink: manage/disable-autosupport.html 
sidebar: sidebar 
keywords:  
summary: 'Quando si configura il sistema di archiviazione per la prima volta, AutoSupport viene attivato per impostazione predefinita. Invia messaggi al supporto tecnico 24 ore dopo l"attivazione.' 
---
= Disattiva AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si configura il sistema di archiviazione per la prima volta, AutoSupport viene attivato per impostazione predefinita. Invia messaggi al supporto tecnico 24 ore dopo l'attivazione. Quando disabiliti AutoSupport, non riceverai più supporto e monitoraggio proattivi.


NOTE: Si consiglia di mantenere attivato AutoSupport. Aiuta a velocizzare il rilevamento e la risoluzione dei problemi. Il sistema raccoglie le informazioni AutoSupport e le memorizza localmente, anche quando è disattivato. Tuttavia, non invia il rapporto a nessuna rete.

.Fasi
. Avviare Gestione strumenti ONTAP da un browser Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Effettua l'accesso con i tool ONTAP per le credenziali di amministratore di VMware vSphere fornite durante l'implementazione.
. Selezionare l'opzione *Impostazioni* > *Telemetria* > *Modifica*.
. Deselezionare l'opzione *AutoSupport* e salvare le modifiche.

