---
permalink: manage/edit-appliance-settings.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile modificare la password dell"amministratore utilizzando ONTAP Tools Manager.' 
---
= Modifica i tool di ONTAP per la configurazione di VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizzare ONTAP Tools Manager per ampliare la configurazione ONTAP tools for VMware vSphere , aumentando il numero di nodi o abilitando l'alta disponibilità (HA).  Per impostazione predefinita, gli ONTAP tools for VMware vSphere vengono distribuiti come configurazione a nodo singolo, non HA.

.Prima di iniziare
* Assicurarsi che il modello OVA abbia la stessa versione OVA del nodo 1. Il nodo 1 è il nodo predefinito in cui vengono inizialmente implementati i tool ONTAP per VMware vSphere OVA.
* Assicurarsi che l'hot add della CPU e l'hot plug della memoria siano abilitati.
* Nel vCenter Server, imposta il livello di automazione del Disaster Recovery Service (DRS) su parzialmente automatizzato. Dopo aver implementato HA, ripristinalo su completamente automatizzato.
* I nomi host dei nodi nella configurazione HA devono essere in minuscolo.


.Fasi
. Avviare Gestione strumenti ONTAP da un browser Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Effettua l'accesso con i tool ONTAP per le credenziali di amministratore di VMware vSphere fornite durante l'implementazione.
. Selezionare *Modifica impostazioni appliance* nella sezione Panoramica.
. Nella sezione *Configurazione*, aumenta le dimensioni del nodo e abilita la configurazione HA.  Utilizzare le credenziali di vCenter Server per apportare modifiche.
+
Nella configurazione HA è possibile modificare i dettagli della libreria dei contenuti.  Fornire la password per ogni modifica.

+

NOTE: Negli ONTAP tools for VMware vSphere è consentito solo aumentare le dimensioni del nodo; non è possibile ridurle.  In una configurazione non HA è supportata solo una configurazione di medie dimensioni.  In una configurazione HA sono supportate configurazioni medie e grandi.

. Utilizzare il pulsante di commutazione ha per abilitare la configurazione ha. Nella pagina *ha settings*, verificare che:
+
** La libreria di contenuti appartiene allo stesso vCenter Server in cui vengono eseguite le macchine virtuali del nodo degli strumenti ONTAP. Le credenziali vCenter Server vengono utilizzate per convalidare e scaricare il modello OVA per le modifiche all'appliance.
** La macchina virtuale che ospita gli strumenti ONTAP non viene implementata direttamente su un host ESXi. La VM deve essere distribuita su un cluster o su un pool di risorse.
+

NOTE: Dopo aver abilitato la configurazione HA, non è possibile tornare a una configurazione a nodo singolo non HA.



. Nella sezione *ha settings* della finestra *Edit Appliance Settings*, è possibile immettere i dettagli dei nodi 2 e 3. I tool ONTAP per VMware vSphere supportano tre nodi nel setup ha.
+

NOTE: Gli strumenti ONTAP precompilano la maggior parte delle opzioni di input con i dettagli della rete Node 1 per semplificare il flusso di lavoro.  È possibile modificare i dati di input prima di passare all'ultima pagina della procedura guidata. È possibile immettere i dettagli dell'indirizzo IPv6 per gli altri due nodi solo quando l'indirizzo IPv6 è abilitato sul nodo di gestione degli strumenti ONTAP .

+
Assicurarsi che un host ESXi contenga solo una VM di strumenti ONTAP. I dati immessi vengono convalidati ogni volta che si passa alla finestra successiva.

. Rivedere i dettagli nella sezione *Riepilogo* e *Salva* le modifiche.


.Quali sono le prossime novità?
La pagina *Panoramica* mostra lo stato della distribuzione. È anche possibile monitorare lo stato del processo di modifica delle impostazioni dell'appliance dalla vista processi utilizzando l'ID processo.

Se la distribuzione HA non riesce e lo stato del nuovo nodo è "Nuovo", eliminare la nuova VM in vCenter prima di provare ad abilitare nuovamente HA.

La scheda *Avvisi* sul pannello di sinistra elenca gli avvisi per gli strumenti ONTAP per VMware vSphere.
