---
permalink: manage/edit-hostcluster-protection.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: È possibile modificare le relazioni SnapMirror del cluster host protetto. È possibile aggiungere, modificare ed eliminare le relazioni. Tuttavia, non è possibile modificare il nome del gruppo di coerenza. 
---
= Modificare il cluster host protetto
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare le impostazioni di protezione per un cluster host in un unico flusso di lavoro.  Sono supportate le seguenti modifiche:

* Aggiungi nuovi datastore o host al cluster protetto.
* Aggiungere nuove relazioni SnapMirror alle impostazioni di protezione.
* Elimina le relazioni SnapMirror esistenti dalle impostazioni di protezione.
* Modificare una relazione SnapMirror esistente.



NOTE: Dopo aver creato, modificato o eliminato la protezione per un cluster host, è necessario eseguire l'individuazione dello storage per riflettere le modifiche.  Se non si esegue la rilevazione dello storage, le modifiche vengono riflesse dopo l'attivazione della rilevazione periodica dello storage.



== Monitoraggio della protezione dei cluster host

Monitorare lo stato di protezione, le relazioni SnapMirror , gli archivi dati e lo stato SnapMirror per ciascun cluster host protetto.

.Fasi
. Accedere al client vSphere.
. Vai a *Strumenti NetApp ONTAP * > *Protezione* > *Relazioni cluster host*.
+
Nella colonna Protezione viene visualizzata un'icona che mostra lo stato della protezione.

. Passare il mouse sull'icona per visualizzare ulteriori dettagli.




== Aggiungere nuovi datastore o host

Aggiungere host o creare datastore sul cluster protetto utilizzando l'interfaccia utente di vCenter.

.Fasi
. Accedere al client vSphere.
. Per modificare le proprietà di un cluster protetto, è possibile effettuare una delle seguenti operazioni
+
.. Vai a *Strumenti NetApp ONTAP * > *Protezione* > *Relazioni cluster host*, seleziona il menu con i puntini di sospensione accanto al cluster e seleziona *Modifica* o
.. Fare clic con il pulsante destro del mouse su un cluster host e selezionare *Strumenti NetApp ONTAP * > *Proteggi cluster*.


. Se si crea un datastore nell'interfaccia utente di vCenter, questo appare come non protetto.  È possibile visualizzare tutti i datastore nel cluster e il loro stato di protezione in una finestra di dialogo.  Selezionare il pulsante *Proteggi* per abilitare la protezione.
+

NOTE: Dopo aver creato un datastore nell'interfaccia utente di vCenter Server, selezionare *Scopri* nella pagina di panoramica per visualizzare il datastore come candidato per la protezione nel cluster host.  Lo stato di protezione viene aggiornato in protetto dopo la successiva rilevazione periodica della protezione.

. Se si aggiunge un nuovo host ESXi, lo stato di protezione viene visualizzato come parzialmente protetto.  Selezionare il menu con i puntini di sospensione nelle impostazioni SnapMirror e selezionare *Modifica* per impostare la prossimità dell'host ESXi appena aggiunto.
+

NOTE: Per le relazioni asincrone, la modifica non è supportata negli strumenti ONTAP perché l'SVM di destinazione per un sito terziario non può essere aggiunto alla stessa istanza.  Per modificare la configurazione della relazione, utilizzare System Manager o la CLI sulla SVM di destinazione.

. Dopo aver apportato le modifiche, seleziona *Salva*.
. Le modifiche sono visibili nella finestra *Proteggi cluster*.


Gli strumenti ONTAP creano un'attività vCenter e puoi monitorarne l'avanzamento nel pannello *Attività recente*.



== Aggiungi una nuova relazione SnapMirror

.Fasi
. Accedere al client vSphere.
. Per modificare le proprietà di un cluster protetto, è possibile effettuare una delle seguenti operazioni
+
.. Vai a *Strumenti NetApp ONTAP * > *Protezione* > *Relazioni cluster host*, seleziona il menu con i puntini di sospensione sul cluster e seleziona *Modifica* o
.. Fare clic con il pulsante destro del mouse su un cluster host e selezionare *Strumenti NetApp ONTAP * > *Proteggi cluster*.


. Selezionare *Aggiungi relazione*.
. Aggiungere una nuova relazione come tipo di criterio *Asynchronous* o *AutomatedFailOverDuplex*.
. Selezionare *Proteggi*.
+
Le modifiche sono visibili nella finestra *Proteggi cluster*.



Gli strumenti ONTAP creano un'attività vCenter e puoi monitorarne l'avanzamento nel pannello *Attività recente*.



== Eliminare una relazione SnapMirror esistente

Per eliminare una relazione asincrona SnapMirror , assicurarsi che il sito secondario SVM o cluster sia aggiunto come backend di archiviazione negli ONTAP tools for VMware vSphere.  Non è possibile eliminare tutte le relazioni SnapMirror contemporaneamente.  L'eliminazione di una relazione comporta anche la rimozione della relazione corrispondente dal cluster ONTAP .  Quando si elimina una relazione Automated Failover Duplex SnapMirror , il sistema annulla la mappatura dei datastore di destinazione ed elimina il gruppo di coerenza, i LUN, i volumi e gli igroup dal cluster ONTAP di destinazione.

Quando si elimina la relazione, il sistema esegue nuovamente la scansione del sito secondario per rimuovere la LUN non mappata come percorso attivo dagli host.

.Fasi
. Accedere al client vSphere.
. Per modificare le proprietà di un cluster protetto, è possibile effettuare una delle seguenti operazioni
+
.. Vai a *Strumenti NetApp ONTAP * > *Protezione* > *Relazioni cluster host*, seleziona il menu con i puntini di sospensione sul cluster e seleziona *Modifica* o
.. Fare clic con il pulsante destro del mouse su un cluster host e selezionare *Strumenti NetApp ONTAP * > *Proteggi cluster*.


. Selezionare il menu puntini di sospensione nelle impostazioni SnapMirror e selezionare *Elimina*.
+
** Se si elimina una relazione basata sul tipo di policy asincrona di un cluster host protetto, è necessario rimuovere manualmente gli elementi di archiviazione dal cluster di archiviazione terziario.  Gli elementi di archiviazione includono gruppi di coerenza, volumi (per i sistemi ONTAP ), unità di archiviazione (LUN/Namespace) e snapshot.
** Se si elimina una relazione basata su policy Automated Failover Duplex (AFD) di un cluster host protetto, è possibile scegliere di rimuovere gli elementi di archiviazione associati sull'archiviazione secondaria direttamente dall'interfaccia.
** Se si elimina una relazione basata su criteri AFD (Automated Failover Duplex) e il gruppo di coerenza è ora gerarchico per i backup a livello di applicazione, viene visualizzato un avviso relativo all'impatto sul backup.  Conferma per procedere.  Dopo la conferma, eliminare gli elementi di archiviazione associati nell'archiviazione secondaria.  Se non vengono rimossi, rimangono nel sito secondario.




Gli strumenti ONTAP creano un'attività vCenter e puoi monitorarne l'avanzamento nel pannello *Attività recente*.



== Modificare una relazione SnapMirror esistente

Per modificare una relazione asincrona SnapMirror , assicurarsi che il sito secondario SVM o cluster sia aggiunto come backend di archiviazione negli ONTAP tools for VMware vSphere.  Per le relazioni Automated Failover Duplex SnapMirror , è possibile aggiornare la prossimità dell'host per configurazioni uniformi o l'accesso dell'host per configurazioni non uniformi.  Non è supportato il passaggio tra i tipi di policy Duplex di failover asincrono e automatico.  È possibile configurare le impostazioni di prossimità o di accesso per gli host appena scoperti nel cluster.


NOTE: Non è possibile modificare una relazione asincrona SnapMirror esistente.

.Fasi
. Accedere al client vSphere.
. Per modificare le proprietà di un cluster protetto, è possibile effettuare una delle seguenti operazioni
+
.. Vai a *Strumenti NetApp ONTAP * > *Protezione* > *Relazioni cluster host*, seleziona il menu con i puntini di sospensione sul cluster e seleziona *Modifica* o
.. Fare clic con il pulsante destro del mouse su un cluster host e selezionare *Strumenti NetApp ONTAP * > *Proteggi cluster*.


. Se è selezionato il tipo di policy AutomatedFailOverDuplex, aggiungere i dettagli di prossimità dell'host o di accesso all'host.
. Selezionare il pulsante *Proteggi*.


Gli strumenti ONTAP creano un'attività vCenter.  Segui i progressi nel pannello *Attività recenti*.
