---
permalink: manage/edit-esxi-host-settings.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile utilizzare la dashboard dei tool ONTAP per VMware vSphere per modificare le impostazioni dell"host ESXi.' 
---
= Modificare le impostazioni degli host ESXi utilizzando gli strumenti ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizzare la dashboard degli strumenti ONTAP in VMware vSphere per identificare i problemi di configurazione, selezionare gli host ESXi, rivedere le impostazioni consigliate NetApp e applicarle.

.Prima di iniziare
Il portlet dei sistemi host ESXi visualizza i problemi con le impostazioni dell'host ESXi.  Seleziona un problema per visualizzare il nome host o l'indirizzo IP.

.Fasi
. Accedere al client vSphere.
. Nella pagina Collegamenti, selezionare *NetApp ONTAP tools* nella sezione dei plug-in.
. Accedere al portlet *ESXi host compliance* nella Panoramica (dashboard) degli strumenti ONTAP per il plug-in VMware vSphere.
. Selezionare il collegamento *Applica impostazioni consigliate*.
. Nella finestra *Applica impostazioni host consigliate*, seleziona gli host per i quali desideri utilizzare le impostazioni host consigliate NetApp e seleziona *Avanti*.
+

NOTE: È possibile espandere l'host ESXi per visualizzare i valori correnti.

. Nella pagina delle impostazioni, selezionare i valori consigliati secondo necessità.
. Nel pannello di riepilogo, controllare i valori e selezionare *fine*. È possibile tenere traccia dell'avanzamento nel riquadro attività recenti.


.Informazioni correlate
link:../configure/configure-esx-server-multipath-and-timeout-settings.html["Configurare le impostazioni dell'host ESXi"]
