---
permalink: manage/enable-services.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile modificare la password dell"amministratore utilizzando Gestione strumenti ONTAP per abilitare servizi come provider VASA, importazione della configurazione vVol e disaster recovery (SRA) utilizzando Gestione strumenti ONTAP.' 
---
= Abilita i tool ONTAP per i servizi VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare la password dell'amministratore utilizzando Gestione strumenti ONTAP per abilitare servizi come provider VASA, importazione della configurazione vVol e disaster recovery (SRA) utilizzando Gestione strumenti ONTAP.

.Fasi
. Avviare Gestione strumenti ONTAP da un browser Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Effettua l'accesso con i tool ONTAP per le credenziali di amministratore di VMware vSphere fornite durante l'implementazione.
. Selezionare *Modifica impostazioni appliance* nella sezione Panoramica.
. Nella sezione *Servizi* è possibile abilitare servizi opzionali come VASA Provider, importazione della configurazione vVols e disaster recovery (SRA) in base alle esigenze.
+
Quando si abilitano i servizi per la prima volta, è necessario creare le credenziali del provider VASA e SRA. Vengono utilizzati per registrare o abilitare i servizi VASA Provider e SRA su vCenter Server. Il nome utente può contenere solo lettere, numeri e caratteri di sottolineatura. La lunghezza della password deve essere compresa tra 8 e 256 caratteri.

+

NOTE: Prima di disabilitare qualsiasi servizio opzionale, assicurarsi che i vCenter Server gestiti dagli strumenti ONTAP non li utilizzino.

+
L'opzione *Consenti importazione della configurazione vVols * viene visualizzata solo quando è abilitato il servizio VASA Provider.  Questa opzione consente la migrazione dei dati vVols dagli strumenti ONTAP 9.xx agli strumenti ONTAP 10.5.


