---
permalink: manage/manage-vcenter.html 
sidebar: sidebar 
keywords: manage vCenter instances, add remove vCenter, ONTAP tools vCenter credentials, vCenter certificate management 
summary: Gestisci le istanze di vCenter negli ONTAP tools per controllare host, macchine virtuali e backend di storage. 
---
= Gestire le istanze di vCenter Server negli strumenti ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le istanze di vCenter Server sono piattaforme di gestione centralizzate che ti permettono di controllare host, macchine virtuali e backend di storage. Negli ONTAP tools puoi dissociare i backend di storage, modificare i dettagli delle istanze, rimuovere le istanze e rinnovare i certificati del server vCenter.



[[dissociate-storage-backends-from-a-vcenter-server-instance]]
== Dissocia i backend di storage da un'istanza del server vCenter

La pagina dell'elenco di vCenter Server mostra il numero associato di backend storage. Ogni istanza di vCenter Server può essere associata o dissociata da un backend dello storage.

.Fasi
. Avviare Gestione strumenti ONTAP da un browser Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Effettua l'accesso con i tool ONTAP per le credenziali di amministratore di VMware vSphere fornite durante l'implementazione.
. Seleziona *vCenters* dalla barra laterale.
. Seleziona i tre puntini verticali per il vCenter Server che vuoi associare o dissociare ai backend di storage.
. Selezionare *dissociare il backend di archiviazione*.




[[modify-a-vcenter-server-instance]]
== Modificare un'istanza di vCenter Server

Modifica un'istanza del server vCenter completando i seguenti passaggi.

. Avviare Gestione strumenti ONTAP da un browser Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Effettua l'accesso con i tool ONTAP per le credenziali di amministratore di VMware vSphere fornite durante l'implementazione.
. Seleziona *vCenters* dalla barra laterale.
. Seleziona i tre puntini verticali per il vCenter Server che vuoi modificare e seleziona *Modifica*.
. Nella finestra *Modifica vCenter*, immettere il nome utente, la password e i dettagli della porta.
. Carica il certificato e seleziona *Modifica*.




[[remove-a-vcenter-server-instance]]
== Rimuovere un'istanza di vCenter Server

Puoi rimuovere un'istanza del server vCenter anche quando i datastore e i backend di storage sono ancora associati. La finestra di dialogo *Remove vCenter* ti guida nelle azioni necessarie in base allo stato attuale del server vCenter.


NOTE: L'eliminazione forzata rimuove solo i metadati degli strumenti ONTAP. Non rimuove gli oggetti di storage ONTAP (volumi o LUN), i datastore vSphere o le macchine virtuali.

.Prima di iniziare
L'eliminazione forzata è bloccata se il vCenter Server ha datastore vVols o datastore protetti. Prima di procedere:

* Rimuovi o migra tutti gli archivi dati vVols.
* Rimuovi la protezione da tutti i datastore protetti.
* Assicurati che non siano in esecuzione processi di rilevamento. L'operazione di eliminazione forzata non verrà eseguita se sono in corso processi di rilevamento.



NOTE: I backend di storage globali condivisi con altre istanze del server vCenter vengono mantenuti. Viene rimossa solo l'associazione con il server vCenter eliminato.

.Fasi
. Avviare Gestione strumenti ONTAP da un browser Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Effettua l'accesso con i tool ONTAP per le credenziali di amministratore di VMware vSphere fornite durante l'implementazione.
. Seleziona *vCenters* dalla barra laterale.
. Seleziona i tre puntini verticali per il vCenter Server richiesto e seleziona *Rimuovi*.
. Nella finestra di dialogo *Rimuovi vCenter*, controlla lo stato del server vCenter ed esegui le azioni necessarie.
+
Il comportamento della finestra di dialogo dipende dallo stato del vCenter Server:

+
[cols="2,2,3"]
|===
| Condizione | Comportamento della finestra di dialogo | Azione richiesta 


| Nessun vVols o archivi dati protetti, ma i backend di storage sono associati | La finestra di dialogo visualizza il numero di storage backend e datastore associati. | Seleziona *Rimuovi tutti gli artefatti di storage da questo vCenter Server* e *Capisco che i datastore associati non saranno più gestiti da ONTAP tools*. 


| Nessun vVols datastore, datastore protetto o backend di storage | La finestra di dialogo conferma la rimozione. | Non è richiesta alcuna azione aggiuntiva. 
|===
. Seleziona *Eliminazione forzata*.
. Conferma l'azione.


.Risultato
Gli strumenti ONTAP eseguono automaticamente le seguenti azioni:

* Plug-in non registrato.
* I privilegi dei plug-in e i ruoli dei plug-in vengono rimossi.


L'istanza del server vCenter non è più gestita da ONTAP tools.

Se il vCenter Server non è raggiungibile durante la cancellazione:

* ONTAP tools rimuove il record del server vCenter.
* La deregistrazione del plugin non avviene.
* Viene visualizzato un avviso.
* Devi annullare manualmente la registrazione del plugin da VMware vCenter Server.




[[renew-vcenter-server-certificate]]
== Rinnova il certificato di vCenter Server

Gli strumenti ONTAP ti avvisano quando il certificato vCenter sta per scadere o è scaduto. Dopo aver rinnovato il certificato vCenter, caricare il nuovo certificato negli strumenti ONTAP seguendo i passaggi seguenti:

. Accedere alla shell di diagnostica remota degli strumenti ONTAP .
. Ottenere il certificato vCenter rinnovato dalla shell di diagnostica:
+
[listing]
----
echo | openssl s_client connect <vcenter>:443 2>&1 | sed -n '/-BEGIN CERTIFICATE/,/END CERTIFICATE/p'
----
. Verifica che il certificato sia in formato ASCII Base 64 e che includa le righe di inizio e fine, ad esempio:
+
[listing]
----
---{}BEGIN CERTIFICATE{}---
MIIFUzCCA7ugAwIBAgIJANOgLapcl5oSMA0GCSqGSIb3DQEBCwUAMIGJMQwwCgYD
VQQDDAN2YzExFDASBgoJkiaJk/IsZAEZFgRkZW1vMRUwEwYKCZImiZPyLGQBGRYF
bG9jYWwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRwwGgYDVQQK
DBN2YzEuZGVtby5uZXRhcHAuY29tMQwwCgYDVQQLDANMT0QwHhcNMjQwNDA1MTgw
NTE4WhcNMjYwNDA1MTgwNTE4WjBzMRwwGgYDVQQDDBN2YzEuZGVtby5uZXRhcHAu
Y29tMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTESMBAGA1UEBwwJ
UGFsbyBBbHRvMQ8wDQYDVQQKDAZOZXRBcHAxDDAKBgNVBAsMA0xPRDCCAaIwDQYJ
KoZIhvcNAQEBBQADggGPADCCAYoCggGBALU8OCWMtA2gvIC/OTw/7xucvPVuM+b8
DhzvNpQ2phjfr6ctEhbntPpqPdu+t2CKK7l0mzg3D9cJ/rvMvdDDXr0tgaD1oi2u
ZDW0CaF0QhLOpNfRXMoogBZ66csEhViAy3CHTcOse770mA/PyoHgrCPZngVlZIiQ
TIWpdQMbEEzFIkrLfC70UW2MzfublrsH7Dn/kOu/iCSlVJWixKf7SmZtVQ5ZxBTD
UlJSiqoX1eRXGyunArEvrIpOY9kkKXUElm3hGnk/ZmiuBJ+HqUYqYW+H+7vE3lKa
6NEqDX+tZotxTx2bXMjeiIWU30ZbshgeXlIG9qc49clBoC9iGjavhctOcaXg/W3h
dLKK5ds3rpRERgMg6VMkrfiqAJuiq+b3sTvXMAul/3hL7hz5QABAE/hP4ZvIHV02
WWDQRLiuVFAcDAyvCrO9Irx0Gk1RyRShKYakdWxZ3hhMdLuGq0yvRXqo1Ib94zwO
JfBJHjFToA/GqwromZgiTzJkKq5xbN8MFwIDAQABo4HSMIHPMAsGA1UdDwQEAwIF
4DA7BgNVHREENDAygRVlbWFpbEBkZW1vLm5ldGFwcC5jb22HBMCoAB+CE3ZjMS5k
ZW1vLm5ldGFwcC5jb20wHQYDVR0OBBYEFJ0V0zY+JRpFrEt31ovAY4BLFXmAMB8G
A1UdIwQYMBaAFENf6fRxWF3OJQNTPIdUpK6kjA78MEMGCCsGAQUFBwEBBDcwNTAz
BggrBgEFBQcwAoYnaHR0cHM6Ly92YzEuZGVtby5uZXRhcHAuY29tL2FmZC92ZWNz
L2NhMA0GCSqGSIb3DQEBCwUAA4IBgQBaDfk7GBM4vmhzYCqGrr6KB+h3qeTJ+Y0Y
5nIPRP1HucawDQ8QTay605ddJ8gFGoxkOQDn9tdXWXGjnTRFOT8R+Hw/nUfVSiDP
sYienb16copzUNwtqh+m9Ifow74Gf+ulRzEC0EAVO1X/nTEYH6NKM6Wy7y7F8g5J
lrpM3JY90ZChMqHO3Av/88rbErfQ/gU1brJ3u9Gks4e20Z7Ff312ZKhWRuJDlN2Z
0tc/gp90N9GxaVvELovq/pdjaZ8xiXCxa6piicrJd9WnqMH1gmxP2PIBDxMDBWBG
gwsfs5H7VG9MJYks6lViNsGclo0EwEdF0MfoB3JtsWpPWq6+jBua0Jm7/aFCU+Ht
mykr0gaV7muegoiBQuDma4EkAI31D7ZlUgJQaw157NTk4RW3TFcbtViBHJkM54Hr
iVm0cl+2BZNi/QTMh/MkWV2dYXJ3NuNlqqfzFY+bUfkzkR4SneMk0HX3joNNYDJv
siO7bL+k/Pxql27NVIhuCoVJAlcI7ak=
---{}END CERTIFICATE{}---
----
. Copia l'output e salvalo come file di testo con un `.pem` estensione sul desktop.
. Avviare Gestione strumenti ONTAP da un browser Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Effettua l'accesso con i tool ONTAP per le credenziali di amministratore di VMware vSphere fornite durante l'implementazione.
. Seleziona l'istanza vCenter Server applicabile dalla barra laterale
. Seleziona i tre puntini verticali per il vCenter Server che vuoi modificare e seleziona *Modifica*.
. Nella finestra *Modifica vCenter*, immettere il nome utente, la password e i dettagli della porta.
. Carica il certificato e seleziona *Modifica*.


.Informazioni correlate
link:../manage/configure-remote-diagnostic-access.html["Configurare l'accesso remoto alla diagnostica"]
