---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords:  
summary: Dovresti essere consapevole di alcune considerazioni durante la migrazione di macchine virtuali esistenti nel tuo data center. 
---
= Considerazioni sulla migrazione e la clonazione di macchine virtuali per ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È importante tenere presenti alcune considerazioni relative alla migrazione delle macchine virtuali esistenti nel data center.



== Migrazione di macchine virtuali protette

È possibile migrare le macchine virtuali protette in:

* Stesso datastore vVol in un host ESXi diverso
* Datastore vVol compatibile diverso nello stesso host ESXi
* Datastore vVol compatibile diverso in un host ESXi diverso


Se si migra la macchina virtuale su un FlexVol volume diverso, il sistema aggiorna il file di metadati per quel volume con le informazioni sulla macchina virtuale. Se una macchina virtuale viene migrata su un host ESXi diverso ma con lo stesso storage, il file di metadati FlexVol volume sottostante non verrà modificato.



== Clonare macchine virtuali protette

È possibile clonare le macchine virtuali protette nei seguenti modi:

* Stesso container dello stesso volume FlexVol che utilizza un gruppo di replica
+
Il file di metadati dello stesso volume FlexVol viene aggiornato con i dettagli della macchina virtuale clonata.

* Stesso container di un volume FlexVol diverso che utilizza un gruppo di replica
+
Il volume FlexVol in cui viene posizionata la macchina virtuale clonata, il file di metadati viene aggiornato con i dettagli della macchina virtuale clonata.

* Datastore di vVol o container diverso
+
Il volume FlexVol in cui viene posizionata la macchina virtuale clonata, il file di metadati viene aggiornato con i dettagli della macchina virtuale.



Attualmente VMware non supporta macchine virtuali clonate in un modello VM.

È supportato il clone di una macchina virtuale protetta.

Per ulteriori dettagli, fare riferimento https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html["Creazione di una macchina virtuale per la clonazione"] a.



== Snapshot delle macchine virtuali

Attualmente sono supportate solo le istantanee delle macchine virtuali senza memoria. Se la macchina virtuale dispone di Snapshot con memoria, la macchina virtuale non viene presa in considerazione per la protezione.

Non è inoltre possibile proteggere macchine virtuali non protette dotate di snapshot di memoria.  Per questa versione, è previsto che tu elimini lo snapshot della memoria prima di abilitare la protezione per la macchina virtuale.

Per una VM Windows con tipo di archiviazione ASA r2, uno snapshot della macchina virtuale è di sola lettura.  Quando si accende la VM, VASA Provider crea una LUN dallo snapshot di sola lettura e abilita gli IOPS.  Quando si spegne la VM, VASA Provider elimina la LUN e disabilita gli IOPS.
