---
permalink: manage/migrate-standard-virtual-machines-to-vvols-datastores.html 
sidebar: sidebar 
keywords: migrate VMs to vVols, NFS VMFS to vVol migration, virtual machine storage migration, policy-based VM storage 
summary: Migra le macchine virtuali dai datastore NFS e VMFS ai datastore vVols per la gestione basata su policy. 
---
= Migrare le macchine virtuali negli archivi dati vVols in ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile migrare le macchine virtuali dai datastore NFS e VMFS ai datastore Virtual Volumes (vVol), per sfruttare la gestione delle macchine virtuali basata su policy e altre funzionalità vVol. I datastore di vVol consentono di soddisfare i requisiti di carico di lavoro più elevati.

.Prima di iniziare
Verifica che VASA Provider non sia in esecuzione su nessuna delle macchine virtuali che intendi migrare. Se migri una macchina virtuale su cui è in esecuzione VASA Provider verso un vVols datastore, non puoi eseguire nessuna operazione di gestione, incluso l'avvio delle macchine virtuali presenti su vVols datastore.

.A proposito di questa attività
Quando esegui la migrazione da un datastore NFS e VMFS a un datastore vVol, vCenter Server utilizza le API vStorage per l'integrazione degli array (VAAI) per eseguire l'offload del carico durante lo spostamento dei dati dai datastore VMFS, ma non da un file NFS VMDK. Gli offload VAAI riducono normalmente il carico sull'host.

.Fasi
. Fare clic con il pulsante destro del mouse sulla macchina virtuale da migrare e selezionare *Migra*.
. Selezionare *Cambia solo memoria*, quindi selezionare *Avanti*.
. Selezionare un formato di disco virtuale, una policy di archiviazione della VM e un datastore vVol che corrispondano alle funzionalità del datastore che si sta migrando.
. Controllare le impostazioni e selezionare *fine*.

