---
permalink: manage/mount-a-vvols-datastore.html 
sidebar: sidebar 
keywords: mount vVols datastore, add vVol datastore to hosts, ONTAP tools vVol host access, VMware virtual volumes mount 
summary: Monta un vVols datastore su host aggiuntivi per fornire accesso allo storage in tutto il tuo ambiente virtuale. 
---
= Montare un datastore vVols negli ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi montare un datastore VMware Virtual Volumes (vVols) su uno o più host aggiuntivi per fornire accesso allo storage ad altri host. Puoi smontare un datastore vVols solo tramite API a livello di host. Lo smontaggio di un datastore a livello di cluster non è supportato.


NOTE: Dopo aver aggiunto l'host, aspetta che il rilevamento pianificato dell'host sia completato prima che venga visualizzato in ONTAP tools. In alternativa, puoi avviare manualmente il rilevamento dalla schermata panoramica di NetApp ONTAP tools. Per informazioni su come aggiungere un host ESXi al tuo cluster vSphere, consulta  https://techdocs.broadcom.com/["Documentazione Tecnica Broadcom"].

.Fasi
. Dalla home page di vSphere Client, selezionare *host e cluster*.
. Nel riquadro di navigazione, selezionare il centro dati che contiene l'archivio dati.
. Fare clic con il pulsante destro del mouse sul datastore e selezionare *NetApp ONTAP tools* > *Mount datastore*.
. Nella finestra di dialogo *Mount Datastore on hosts*, selezionare gli host su cui si desidera montare il datastore, quindi selezionare *Mount*.


Il pannello delle attività recenti mostra lo stato di avanzamento.

.Argomento correlato
link:../manage/add-vsphere-host.html["Aggiungi nuovi host VMware vSphere"]
