---
permalink: manage/mount-datastores-on-host.html 
sidebar: sidebar 
keywords: mount NFS VMFS datastore, datastore host access, ONTAP tools datastore mounting, add datastore to ESXi host 
summary: 'Monta i datastore sugli host aggiuntivi dopo aver aggiunto gli host all"ambiente VMware.' 
---
= Montare i datastore NFS e VMFS negli ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il montaggio di un datastore consente l'accesso allo storage a host aggiuntivi dopo che li hai aggiunti all'ambiente VMware.


NOTE: Dopo aver aggiunto l'host, aspetta che il rilevamento pianificato dell'host sia completato prima che venga visualizzato in ONTAP tools. In alternativa, puoi avviare manualmente il rilevamento dalla schermata panoramica di NetApp ONTAP tools. Per informazioni su come aggiungere un host ESXi al tuo cluster vSphere, consulta  https://techdocs.broadcom.com/["Documentazione Tecnica Broadcom"].

.A proposito di questa attività
* Alcune azioni del pulsante destro del mouse sono disattivate o non disponibili a seconda della versione del client vSphere e del tipo di datastore selezionato.
+
** Se si utilizza vSphere client 8,0 o versioni successive, alcune delle opzioni del pulsante destro del mouse sono nascoste.
** Da vSphere 7.0U3 a vSphere 8.0, anche se le opzioni sono presenti, l'azione è disabilitata.


* vSphere disabilita l'opzione di montaggio del datastore quando il cluster host è protetto con configurazioni uniformi.


.Fasi
. Dalla home page di vSphere Client, selezionare *host e cluster*.
. Nel riquadro di spostamento di sinistra, selezionare i data center contenenti gli host.
. Per montare datastore NFS/VMFS su un host o un cluster di host, fare clic con il pulsante destro del mouse e selezionare *Strumenti NetApp ONTAP * > *Monta datastore*.
. Selezionare gli archivi dati che si desidera montare e selezionare *Mount*.


.Quali sono le prossime novità?
È possibile tenere traccia dell'avanzamento nel riquadro attività recenti.

.Argomento correlato
link:../manage/add-vsphere-host.html["Aggiungi nuovi host VMware vSphere"]
