---
permalink: manage/remove-storage-from-a-vvols-datastore.html 
sidebar: sidebar 
keywords: Remove vVol datastore 
summary: 'L"azione Elimina archivio dati elimina il datastore quando non sono presenti vVol nel datastore selezionato.' 
---
= Restringere il datastore vVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questa sezione spiega come rimuovere volumi da un datastore vVols .

È possibile utilizzare l'azione di rimozione dello storage dal datastore su qualsiasi datastore vVols rilevato o gestito dagli ONTAP tools for VMware vSphere in vCenter Server.

Non è possibile rimuovere l'archiviazione da un volume se contiene vVols; l'opzione di rimozione sarà disabilitata per tali volumi.  Quando si rimuovono volumi dal datastore, è anche possibile eliminare i volumi selezionati dall'archiviazione ONTAP .


NOTE: L'operazione di riduzione del datastore vVols non è supportata per i datastore vVols basati sui sistemi ASA r2.

.Fasi
. Dalla home page di vSphere Client, selezionare *host e cluster*.
. Nel riquadro di navigazione, selezionare il centro dati che contiene l'archivio dati.
. Fare clic con il pulsante destro del mouse sul datastore vVol e selezionare *Strumenti NetApp ONTAP* > *Rimuovi storage dal datastore*.
. Selezionare i volumi che non hanno vVols e selezionare *Rimuovi*.
+

NOTE: L'opzione per selezionare il volume su cui risiede vVols è disabilitata.

. Nella finestra pop-up *Rimuovi storage*, seleziona la casella di controllo *Elimina volumi dal cluster ONTAP* per eliminare i volumi dal datastore e dallo storage ONTAP e seleziona *Elimina*.

