---
permalink: manage/remove-storage-from-a-vvols-datastore.html 
sidebar: sidebar 
keywords: shrink vVols datastore, remove storage from vVol datastore, ONTAP tools vVol capacity reduction, virtual volumes datastore resize down 
summary: Elimina un vVols datastore solo quando non rimangono vVols nel datastore selezionato. 
---
= Ridurre un datastore vVols negli ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizza l'azione "Rimuovi storage dal datastore" per rimuovere i volumi da un vVols datastore in ONTAP tools, riducendone la capacità quando lo storage aggiuntivo non è più necessario.

Utilizzare l'azione di rimozione dello storage dal datastore su qualsiasi datastore vVols gestito dagli strumenti ONTAP in vCenter Server.

Non puoi rimuovere lo storage da un volume se contiene vVols; l'opzione di rimozione è disabilitata per tali volumi. Quando rimuovi i volumi dal datastore, hai anche la possibilità di eliminare i volumi selezionati dallo storage ONTAP.


NOTE: L'operazione di riduzione del datastore vVols non è supportata per i datastore vVols basati sui sistemi ASA r2.

.Fasi
. Dalla home page di vSphere Client, selezionare *host e cluster*.
. Nel riquadro di navigazione, selezionare il centro dati che contiene l'archivio dati.
. Fare clic con il pulsante destro del mouse sul datastore vVol e selezionare *Strumenti NetApp ONTAP* > *Rimuovi storage dal datastore*.
. Selezionare i volumi che non hanno vVols e selezionare *Rimuovi*.
+

NOTE: L'opzione per selezionare il volume su cui vVols risiedono è disabilitata.

. Nella finestra a comparsa *Rimuovi storage*, seleziona la casella di controllo *Elimina volumi dal cluster ONTAP* per eliminare i volumi dal datastore e dallo storage ONTAP, quindi seleziona *Elimina*.

