---
permalink: manage/reports.html 
sidebar: sidebar 
keywords:  
summary: I tool ONTAP per il plug-in VMware vSphere forniscono report su macchine virtuali e datastore. 
---
= Report sui tool ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I tool ONTAP per il plug-in VMware vSphere forniscono report su macchine virtuali e datastore. Quando si seleziona l'icona degli strumenti NetApp ONTAP per il plug-in VMware vSphere nella sezione Collegamenti del client vCenter, l'interfaccia utente passa alla pagina Panoramica. Selezionare la scheda rapporti per visualizzare la macchina virtuale e il report degli archivi dati.

Il report Macchine virtuali mostra l'elenco delle macchine virtuali rilevate (dovrebbero avere almeno un disco da datastore basati su storage ONTAP ) con metriche delle prestazioni. Quando si espande il record della VM, l'interfaccia visualizza tutte le informazioni relative al datastore relative al disco.

Il report sui datastore elenca gli ONTAP tools for VMware vSphere rilevati o riconosciuti che utilizzano qualsiasi storage ONTAP , con metriche delle prestazioni.

È possibile utilizzare l'opzione Gestisci colonne per nascondere o visualizzare colonne diverse.
