---
permalink: manage/reset-manager-password.html 
sidebar: sidebar 
keywords:  
summary: Se si è dimenticata la password di ONTAP Tools Manager, è possibile reimpostare le credenziali di amministratore utilizzando il token generato dagli strumenti ONTAP per la console di manutenzione di VMware vSphere. 
---
= Reimpostare la password di gestione degli strumenti ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si dimentica la password di ONTAP Tools Manager, è possibile ripristinare l'accesso amministratore utilizzando un token di reimpostazione generato dalla console di manutenzione ONTAP tools for VMware vSphere .

.Fasi
. Apri un browser web e vai su `https://<ONTAPtoolsIP>:8443/virtualization/ui/` per accedere a ONTAP tools Manager.
. Nella pagina di accesso, seleziona *Reimposta password*.
. Generare un token di reimpostazione della password utilizzando gli ONTAP tools for VMware vSphere :
+
.. Accedere al vCenter Server e aprire la console di manutenzione.
.. Entra `2` per selezionare *Configurazione di sistema*.
.. Entra `3` per selezionare *Cambia password utente 'maint'*.


. Nella finestra di dialogo per la reimpostazione della password, immettere il token di reimpostazione, il nome utente e la nuova password.
. Selezionare *Reimposta* per aggiornare le credenziali.
. Accedi a ONTAP Tools Manager con la nuova password.

