---
permalink: manage/resize-datastores.html 
sidebar: sidebar 
keywords:  
summary: 'Il ridimensionamento di un datastore consente di aumentare lo storage dei file delle macchine virtuali. È possibile modificare le dimensioni di un datastore in base al cambiamento dei requisiti dell"infrastruttura.' 
---
= Ridimensiona i datastore NFS e VMFS negli ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il ridimensionamento di un datastore consente di aumentare lo storage dei file delle macchine virtuali. È possibile modificare le dimensioni di un datastore in base al cambiamento dei requisiti dell'infrastruttura.

.A proposito di questa attività
È possibile aumentare le dimensioni dei datastore NFS e VMFS.  Un FlexVol volume in questi datastore non può ridursi al di sotto delle sue dimensioni attuali, ma può aumentare fino al 120%.

.Fasi
. Dalla home page di vSphere Client, selezionare *host e cluster*.
. Nel riquadro di navigazione, selezionare il centro dati che contiene l'archivio dati.
. Fare clic con il pulsante destro del mouse sul datastore NFS o VMFS e selezionare *NetApp ONTAP tools* > *Ridimensiona datastore*.
. Nella finestra di dialogo Ridimensiona, immettere una nuova dimensione per l'archivio dati e selezionare *OK*.

