---
permalink: manage/uninstall-deployment.html 
sidebar: sidebar 
keywords: uninstall ONTAP tools, remove ONTAP tools deployment, appliance decommission workflow, graceful deployment termination 
summary: Termina correttamente la distribuzione degli ONTAP tools per VMware vSphere. 
---
= Disinstalla la tua distribuzione di ONTAP tools for VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La disinstallazione di ONTAP tools for VMware vSphere elimina tutti i dati negli strumenti, quindi devi completare questi passaggi per terminare correttamente la tua distribuzione ed evitare perdite di dati impreviste.

.Fasi
. Rimuovere o spostare tutte le macchine virtuali dai tool ONTAP per datastore gestiti da VMware vSphere.
+
** Per rimuovere le macchine virtuali, fare riferimento alla https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-virtual-machine-administration-guide-8-0/managing-virtual-machinesvsphere-vm-admin/adding-and-removing-virtual-machinesvsphere-vm-admin.html#GUID-376174FE-F936-4BE4-B8C2-48EED42F110B-en["Rimuovere e registrare nuovamente le macchine virtuali e i modelli VM"]
** Per spostarli in un datastore non gestito, consulta  https://techdocs.broadcom.com/["Documentazione Tecnica Broadcom"] per la migrazione delle macchine virtuali con Storage vMotion


. link:../manage/delete-ds.html["Elimina datastore"] Creato su tool ONTAP per VMware vSphere.
. Se hai abilitato il provider VASA, seleziona *Impostazioni* > *Impostazioni provider VASA* > *Annulla registrazione* negli strumenti ONTAP per annullare la registrazione dei provider VASA da tutti i server vCenter.
. Disassociare tutti i backend di storage dall'istanza di vCenter Server. Fare riferimento alla link:../manage/manage-vcenter.html["Dissociare i backend di storage con l'istanza di vCenter Server"].
. Eliminare tutti i backend di archiviazione. Fare riferimento alla link:../manage/storage-backend.html["Gestire i back-end dello storage"].
. Rimuovere l'adattatore SRA da VMware Live Site Recovery:
+
.. Accedere come amministratore all'interfaccia di gestione dell'appliance VMware Live Site Recovery utilizzando la porta 5480.
.. Selezionare *schede di replica archiviazione*.
.. Selezionare la scheda SRA appropriata, quindi scegliere *Elimina* dal menu a discesa.
.. Verificare di conoscere i risultati dell'eliminazione della scheda e selezionare *Elimina*.


. Elimina le istanze del server vCenter integrate negli strumenti ONTAP per VMware vSphere. Fare riferimento alla link:../manage/manage-vcenter.html["Gestire le istanze di vCenter Server"].
. Spegnere gli strumenti ONTAP per le VM VMware vSphere da vCenter Server ed eliminare le VM.


.Cosa succederà?
link:../manage/delete-deployment.html["Rimuovere i volumi FlexVol"]
