---
permalink: manage/unmount-datastores-on-host.html 
sidebar: sidebar 
keywords: unmount NFS VMFS datastore, remove datastore from host, ONTAP tools datastore unmount, ESXi host storage detach 
summary: Smonta i datastore NFS o VMFS dagli host ESXi utilizzando ONTAP tools. 
---
= Smonta i datastore NFS e VMFS negli ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Usa questa procedura per smontare un datastore NFS o VMFS dagli host ESXi. Lo smontaggio del datastore a livello di cluster non è supportato tramite l'interfaccia utente o le API.

A partire da ONTAP tools 10.6, lo smontaggio è bloccato per i datastore VMFS protetti.

.Fasi
. Accedere al client vSphere.
. Fai clic con il pulsante destro del mouse su un oggetto datastore NFS o VMFS e seleziona *Smonta datastore*.
+
Il vSphere client apre una finestra di dialogo che elenca gli host ESXi che montano il datastore. Se il datastore è protetto, ONTAP tools blocca la richiesta e mostra un messaggio che indica che il datastore è sotto protezione e non può essere smontato.

. Selezionare uno o più host ESXi per smontare il datastore.
+
Non è possibile smontare il datastore da tutti gli host. L'interfaccia utente suggerisce invece di utilizzare l'operazione di eliminazione dell'archivio dati.

. Selezionare il pulsante *Smonta*.
+
L'opzione *Smonta datastore* è disponibile solo quando l'host viene spostato al di fuori del cluster host protetto.




NOTE: Se un datastore è protetto, devi rimuovere la protezione prima di poterlo smontare.

.Quali sono le prossime novità?
È possibile tenere traccia dell'avanzamento nel pannello attività recenti.
