---
permalink: manage/unmount-datastores-on-host.html 
sidebar: sidebar 
keywords:  
summary: 'L"azione del datastore smonta un datastore NFS o VMFS dagli host ESXi. L"azione di disinstallazione del datastore è abilitata per i datastore NFS e VMFS, rilevati o gestiti dai tool ONTAP per VMware vSphere.' 
---
= Smonta i datastore NFS e VMFS negli ONTAP tools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'azione Smonta datastore rimuove un datastore NFS o VMFS dagli host ESXi.  È disponibile per i datastore rilevati o gestiti dagli ONTAP tools for VMware vSphere.

.Fasi
. Accedere al client vSphere.
. Fare clic con il pulsante destro del mouse su un oggetto datastore NFS o VMFS e selezionare *Smonta datastore*.
+
Il client vSphere apre una finestra di dialogo ed elenca gli host ESXi che montano il datastore. Quando l'operazione viene eseguita su un datastore protetto, sullo schermo viene visualizzato un messaggio di avviso.

. Selezionare uno o più host ESXi per smontare il datastore.
+
Non è possibile smontare il datastore da tutti gli host. L'interfaccia utente suggerisce invece di utilizzare l'operazione di eliminazione dell'archivio dati.

. Selezionare il pulsante *Smonta*.
+
Se l'archivio dati fa parte di un cluster host protetto, viene visualizzato un messaggio di avviso.




NOTE: Se il datastore protetto viene smontato, l'impostazione di protezione esistente potrebbe comportare una protezione parziale. Fare riferimento a link:../manage/edit-hostcluster-protection.html["Modificare il cluster host protetto"] per consentire una protezione completa.

.Quali sono le prossime novità?
È possibile tenere traccia dell'avanzamento nel pannello attività recenti.
