---
permalink: manage/update-proxyurl.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile raccogliere i file di log per gli strumenti ONTAP per VMware vSphere dalle opzioni disponibili negli strumenti ONTAP per l"interfaccia utente grafica \(GUI\) di VMware vSphere. Il supporto tecnico potrebbe richiedere di raccogliere i file di registro per risolvere un problema.' 
---
= Aggiorna URL proxy AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aggiornare l'URL del proxy AutoSupport per garantire il corretto funzionamento della funzione AutoSupport negli scenari in cui viene utilizzato un server proxy per il controllo dell'accesso alla rete o per le misure di protezione. Consente ai dati AutoSupport di essere instradati attraverso il proxy appropriato, garantendo trasmissione e conformità sicure.

.Fasi
. Avviare Gestione strumenti ONTAP da un browser Web: `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. Effettua l'accesso con i tool ONTAP per le credenziali di amministratore di VMware vSphere fornite durante l'implementazione.
. Seleziona *Impostazioni* dalla barra laterale.
. Selezionare l'opzione *Impostazioni* > *Telemetria* > *Modifica*.
. Immettere un *URL proxy* valido e salvare le modifiche.
+
Se si disattiva AutoSupport, anche l'URL proxy viene disattivato.


