---
permalink: manage/update-vcenter-credentials.html 
sidebar: sidebar 
keywords:  
summary: È possibile aggiornare le credenziali vCenter Server e ONTAP utilizzando la console di manutenzione. 
---
= Aggiornare le credenziali vCenter Server e ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiornare l'istanza di vCenter Server e le credenziali ONTAP utilizzando la console di manutenzione.

*Cosa ti serve*

È necessario disporre delle credenziali di accesso per gli utenti di manutenzione.

*A proposito di questa attività*

Se sono state modificate le credenziali per vCenter Server, ONTAP o Data LIF dopo la distribuzione, è necessario aggiornare le credenziali utilizzando questa procedura.

*Fasi*

. Da vCenter Server, aprire una console al provider VASA.
. Accedere come utente di manutenzione.
. Invio `4` Per selezionare Support and Diagnostics (supporto e diagnostica).
. Invio `1` Per selezionare Accedi alla shell diagnostica.
. Invio `y` per procedere.
. Aggiornare le credenziali come richiesto:
+
.. Per aggiornare le credenziali ONTAP, eseguire il comando:
+
--
otv-update --ontapUsername <new username> --ontapPassword <new password>

--
.. Per aggiornare le credenziali vCenter, eseguire il comando:
+
--
otv-update --vcenterUsername <new username> --vcenterPassword <new password>

--
.. Per aggiornare la LIF dati esegui il comando:
+
--
otv-update --dataLif <new Datalif IP>

--



